import LatticeDongKernel
import LatticeDongBinomial
import LatticeResidueProducts
import LatticeOrderedConvolution
import LatticeTripleConvolution
import LatticeTripleLocality
import LatticeDongIntegrand
import LatticeResidueConvolution
import LatticeDongLocality
import LatticeDescendantLocality
import SelectedDescendantLocality
#print axioms HMT.IV.LatticeDongKernel.negative_contraction_binomial
#print axioms HMT.IV.LatticeDongKernel.left_residue_coefficient
#print axioms HMT.IV.LatticeDongKernel.right_residue_coefficient
#print axioms HMT.IV.LatticeDongKernel.negative_right_residue_coefficient
#print axioms HMT.IV.LatticeDongKernel.left_kernel_clear
#print axioms HMT.IV.LatticeDongKernel.right_kernel_clear
#print axioms HMT.IV.LatticeDongKernel.dong_order_split
#print axioms HMT.IV.LatticeDongBinomial.pow_apply_zero_of_le
#print axioms HMT.IV.LatticeDongBinomial.commuting_add_pow_apply_zero
#print axioms HMT.IV.LatticeDongBinomial.neg_pow_apply_zero
#print axioms HMT.IV.LatticeDongBinomial.commuting_sub_pow_apply_zero
#print axioms HMT.IV.LatticeDongBinomial.dong_binomial_bound
#print axioms HMT.IV.LatticeDongBinomial.TriCoefficients
#print axioms HMT.IV.LatticeDongBinomial.firstThird
#print axioms HMT.IV.LatticeDongBinomial.firstSecond
#print axioms HMT.IV.LatticeDongBinomial.secondThird
#print axioms HMT.IV.LatticeDongBinomial.triple_crossings_commute
#print axioms HMT.IV.LatticeDongBinomial.triple_crossings_sub
#print axioms HMT.IV.LatticeDongBinomial.residue
#print axioms HMT.IV.LatticeDongBinomial.residue_secondThird
#print axioms HMT.IV.LatticeDongBinomial.residue_secondThird_pow
#print axioms HMT.IV.LatticeDongBinomial.dong_residue_core
#print axioms HMT.IV.LatticeDongBinomial.dong_residue_bound
#print axioms HMT.IV.LatticeResidueProducts.field_lower_bound
#print axioms HMT.IV.LatticeResidueProducts.leftTerm
#print axioms HMT.IV.LatticeResidueProducts.rightTerm
#print axioms HMT.IV.LatticeResidueProducts.leftTerm_finite
#print axioms HMT.IV.LatticeResidueProducts.rightTerm_finite
#print axioms HMT.IV.LatticeResidueProducts.residueCoefficient
#print axioms HMT.IV.LatticeResidueProducts.residueCoefficient_apply
#print axioms HMT.IV.LatticeResidueProducts.residueCoefficient_bounded
#print axioms HMT.IV.LatticeResidueProducts.residueField
#print axioms HMT.IV.LatticeResidueProducts.residueField_coefficient
#print axioms HMT.IV.LatticeResidueProducts.heisenberg_leftTerm
#print axioms HMT.IV.LatticeResidueProducts.heisenberg_neg_rightTerm
#print axioms HMT.IV.LatticeResidueProducts.heisenberg_residue_eq_normalCoefficient
#print axioms HMT.IV.LatticeResidueProducts.heisenberg_residue_eq_normalField
#print axioms HMT.IV.LatticeResidueProducts.heisenberg_residueField
#print axioms HMT.IV.LatticeOrderedConvolution.FirstBounded
#print axioms HMT.IV.LatticeOrderedConvolution.SecondBounded
#print axioms HMT.IV.LatticeOrderedConvolution.convolution_finite_second
#print axioms HMT.IV.LatticeOrderedConvolution.convolution_finite_first
#print axioms HMT.IV.LatticeOrderedConvolution.crossing_convolution_second
#print axioms HMT.IV.LatticeOrderedConvolution.crossing_convolution_first
#print axioms HMT.IV.LatticeOrderedConvolution.leftKernel_support
#print axioms HMT.IV.LatticeOrderedConvolution.rightKernel_support
#print axioms HMT.IV.LatticeOrderedConvolution.crossing_leftProduct
#print axioms HMT.IV.LatticeOrderedConvolution.crossing_rightProduct
#print axioms HMT.IV.LatticeOrderedConvolution.crossing_leftProduct_iterate
#print axioms HMT.IV.LatticeOrderedConvolution.crossing_rightProduct_iterate
#print axioms HMT.IV.LatticeOrderedConvolution.firstBounded_crossing
#print axioms HMT.IV.LatticeOrderedConvolution.secondBounded_crossing
#print axioms HMT.IV.LatticeOrderedConvolution.firstBounded_crossing_pow
#print axioms HMT.IV.LatticeOrderedConvolution.secondBounded_crossing_pow
#print axioms HMT.IV.LatticeOrderedConvolution.lowerBounded_of_both
#print axioms HMT.IV.LatticeOrderedConvolution.forwardState
#print axioms HMT.IV.LatticeOrderedConvolution.backwardState
#print axioms HMT.IV.LatticeOrderedConvolution.forwardState_secondBounded
#print axioms HMT.IV.LatticeOrderedConvolution.backwardState_firstBounded
#print axioms HMT.IV.LatticeOrderedConvolution.crossing_pow_evaluate
#print axioms HMT.IV.LatticeOrderedConvolution.local_cleared_product_lowerBounded
#print axioms HMT.IV.LatticeTripleConvolution.FirstAdmissible
#print axioms HMT.IV.LatticeTripleConvolution.SecondAdmissible
#print axioms HMT.IV.LatticeTripleConvolution.shift
#print axioms HMT.IV.LatticeTripleConvolution.leftConv
#print axioms HMT.IV.LatticeTripleConvolution.rightConv
#print axioms HMT.IV.LatticeTripleConvolution.firstAdmissible_shift
#print axioms HMT.IV.LatticeTripleConvolution.secondAdmissible_shift
#print axioms HMT.IV.LatticeTripleConvolution.firstAdmissible_sub
#print axioms HMT.IV.LatticeTripleConvolution.secondAdmissible_sub
#print axioms HMT.IV.LatticeTripleConvolution.leftConv_shift
#print axioms HMT.IV.LatticeTripleConvolution.rightConv_shift
#print axioms HMT.IV.LatticeTripleConvolution.leftConv_sub
#print axioms HMT.IV.LatticeTripleConvolution.rightConv_sub
#print axioms HMT.IV.LatticeTripleConvolution.leftConv_zero
#print axioms HMT.IV.LatticeTripleConvolution.rightConv_zero
#print axioms HMT.IV.LatticeTripleConvolution.firstThird_as_shift
#print axioms HMT.IV.LatticeTripleConvolution.firstSecond_as_shift
#print axioms HMT.IV.LatticeTripleConvolution.secondThird_as_shift
#print axioms HMT.IV.LatticeTripleConvolution.secondAdmissible_firstThird
#print axioms HMT.IV.LatticeTripleConvolution.secondAdmissible_secondThird
#print axioms HMT.IV.LatticeTripleConvolution.firstAdmissible_firstThird
#print axioms HMT.IV.LatticeTripleConvolution.firstAdmissible_secondThird
#print axioms HMT.IV.LatticeTripleConvolution.leftConv_firstThird
#print axioms HMT.IV.LatticeTripleConvolution.leftConv_secondThird
#print axioms HMT.IV.LatticeTripleConvolution.rightConv_firstThird
#print axioms HMT.IV.LatticeTripleConvolution.rightConv_secondThird
#print axioms HMT.IV.LatticeTripleConvolution.firstSecond_leftConv
#print axioms HMT.IV.LatticeTripleConvolution.firstSecond_rightConv
#print axioms HMT.IV.LatticeTripleConvolution.firstSecond_pow_leftConv
#print axioms HMT.IV.LatticeTripleConvolution.firstSecond_pow_rightConv
#print axioms HMT.IV.LatticeTripleConvolution.leftConv_pow
#print axioms HMT.IV.LatticeTripleConvolution.rightConv_pow
#print axioms HMT.IV.LatticeTripleConvolution.secondAdmissible_secondThird_pow
#print axioms HMT.IV.LatticeTripleConvolution.firstAdmissible_secondThird_pow
#print axioms HMT.IV.LatticeTripleConvolution.leftConv_firstThird_pow
#print axioms HMT.IV.LatticeTripleConvolution.leftConv_secondThird_pow
#print axioms HMT.IV.LatticeTripleConvolution.rightConv_firstThird_pow
#print axioms HMT.IV.LatticeTripleConvolution.rightConv_secondThird_pow
#print axioms HMT.IV.LatticeTripleConvolution.leftKernel_zero
#print axioms HMT.IV.LatticeTripleConvolution.leftConv_zero_power
#print axioms HMT.IV.LatticeTripleConvolution.rightConv_zero_power
#print axioms HMT.IV.LatticeTripleConvolution.leftConv_nonnegative
#print axioms HMT.IV.LatticeTripleConvolution.rightConv_nonnegative
#print axioms HMT.IV.LatticeTripleLocality.pairCommutator
#print axioms HMT.IV.LatticeTripleLocality.locality_annihilates_pair
#print axioms HMT.IV.LatticeTripleLocality.leftOfBC
#print axioms HMT.IV.LatticeTripleLocality.rightOfBC
#print axioms HMT.IV.LatticeTripleLocality.leftOfAC
#print axioms HMT.IV.LatticeTripleLocality.rightOfAC
#print axioms HMT.IV.LatticeTripleLocality.secondThird_leftOfBC
#print axioms HMT.IV.LatticeTripleLocality.secondThird_rightOfBC
#print axioms HMT.IV.LatticeTripleLocality.firstThird_leftOfAC
#print axioms HMT.IV.LatticeTripleLocality.firstThird_rightOfAC
#print axioms HMT.IV.LatticeTripleLocality.firstThird_secondThird_commute
#print axioms HMT.IV.LatticeTripleLocality.firstSecond_secondThird_commute
#print axioms HMT.IV.LatticeTripleLocality.rawLeft
#print axioms HMT.IV.LatticeTripleLocality.rawRight
#print axioms HMT.IV.LatticeTripleLocality.rawLeft_decomposition
#print axioms HMT.IV.LatticeTripleLocality.rawRight_decomposition
#print axioms HMT.IV.LatticeTripleLocality.rawLeft_annihilated
#print axioms HMT.IV.LatticeTripleLocality.rawRight_annihilated
#print axioms HMT.IV.LatticeTripleLocality.commutatorWithC
#print axioms HMT.IV.LatticeTripleLocality.firstSecond_commutatorWithC
#print axioms HMT.IV.LatticeTripleLocality.raw_difference_decomposition
#print axioms HMT.IV.LatticeTripleLocality.rawDifference_annihilated
#print axioms HMT.IV.LatticeTripleLocality.rawDifference_annihilated_after_secondThird
#print axioms HMT.IV.LatticeTripleLocality.evaluate
#print axioms HMT.IV.LatticeTripleLocality.evaluate_firstThird_pow
#print axioms HMT.IV.LatticeTripleLocality.evaluate_firstSecond_pow
#print axioms HMT.IV.LatticeTripleLocality.evaluate_secondThird_pow
#print axioms HMT.IV.LatticeTripleLocality.rawLeft_annihilated_on_vector
#print axioms HMT.IV.LatticeTripleLocality.rawRight_annihilated_on_vector
#print axioms HMT.IV.LatticeTripleLocality.rawDifference_annihilated_on_vector
#print axioms HMT.IV.LatticeDongIntegrand.rawLeft_secondAdmissible
#print axioms HMT.IV.LatticeDongIntegrand.rawRight_firstAdmissible
#print axioms HMT.IV.LatticeDongIntegrand.integrand
#print axioms HMT.IV.LatticeDongIntegrand.integrand_first_annihilator
#print axioms HMT.IV.LatticeDongIntegrand.integrand_second_annihilator
#print axioms HMT.IV.LatticeDongIntegrand.integrand_second_annihilator_with_factor
#print axioms HMT.IV.LatticeDongIntegrand.integrand_residue_locality
#print axioms HMT.IV.LatticeResidueConvolution.leftProduct_residue_nat
#print axioms HMT.IV.LatticeResidueConvolution.rightProduct_residue_nat
#print axioms HMT.IV.LatticeResidueConvolution.leftProduct_forward_residue
#print axioms HMT.IV.LatticeResidueConvolution.rightProduct_backward_residue
#print axioms HMT.IV.LatticeResidueConvolution.leftConv_raw_residue
#print axioms HMT.IV.LatticeResidueConvolution.rightConv_raw_residue
#print axioms HMT.IV.LatticeResidueConvolution.residue_convolution_commutator
#print axioms HMT.IV.LatticeDongLocality.residueField_localAt
#print axioms HMT.IV.LatticeDongLocality.residueField_local
#print axioms HMT.IV.LatticeDongLocality.normalField_localAt
#print axioms HMT.IV.LatticeDongLocality.normalField_local
#print axioms HMT.IV.LatticeDescendantLocality.heisenberg_descendant_local
#print axioms HMT.IV.LatticeDescendantLocality.charged_descendant_local
#print axioms HMT.IV.LatticeDescendantLocality.descendant_fields_local
#print axioms HMT.IV.LatticeDescendantLocality.local_linear_extension
#print axioms HMT.IV.LatticeDescendantLocality.stateField_basis_local
#print axioms HMT.IV.LatticeDescendantLocality.stateField_local
#print axioms HMT.I.SelectedDescendantLocality.selected_fields_local
#print axioms HMT.I.SelectedDescendantLocality.selected_local_state_field_publication
