#!/usr/bin/env python3
"""Check the frozen 122-module base, then compile only FoundationRegression.

The baseline and contract digest are deliberately frozen accepted inputs, never
regenerated by this program; changing either requires an explicit review. All
package access is read-only. --self-test uses temporary fixtures and invokes no Lean.
An output directory must be new/empty and outside the sealed package. This test
reuses receipted objects; it is not a fresh compilation of upstream Lean/Mathlib.
"""

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import types


sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent
BASELINE_PATH = HERE / 'FOUNDATION_BASELINE.json'
BASELINE_SHA256 = '77bd36505bbb1ac65d4ba404c5630f5264cd877c6ca66fe00146c139374cd17f'
# Accepted after the first successful compilation, not learned from candidate input.
CONTRACT_SHA256 = 'f63dcf1e3b55c8b3cab04364e33581ff23f4e0977579b9150ac3f58145961052'
ALLOWED_AXIOMS = {'propext', 'Classical.choice', 'Quot.sound', 'Lean.ofReduceBool'}
EXPECTED_QUERIES = {
    'HMT.Shared.FoundationRegression.' + name for name in (
        'app_trit_at_every_visit', 'unique_regional_seeds', 'lifts_reconstruct_records', 'lifts_are_unique',
        'lift_histories_truncate', 'recorded_history_is_retained', 'nonadic_phase_and_memory',
        'recorded_nonadic_return_is_not_reset', 'joint_publication_at_any_scale',
        'publication_at_every_depth', 'publication_retains_all_prefixes',
        'pi_e_phi_recognition_at_every_depth', 'shared_register_is_selected',
        'alpha_uses_selected_register', 'high_support_uses_selected_register',
        'precarry_uses_selected_register', 'alpha_at_every_depth',
        'shared_action_electron_contract', 'shared_incidence_lattice_contract',
    )
}
CONTRACT_IMPORTS = ['SharedArticleIBase', 'CommonComposition', 'RegionalPublicationComposition']


class ContractFailure(RuntimeError):
    pass


def require(condition, message):
    if not condition:
        raise ContractFailure(message)


def sha_bytes(data):
    return hashlib.sha256(data).hexdigest()


def sha_file(path):
    digest = hashlib.sha256()
    with Path(path).open('rb') as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()


def json_file(path):
    return json.loads(Path(path).read_text(encoding='utf-8'))


def safe_child(root, relative):
    relative = Path(relative)
    require(not relative.is_absolute() and '..' not in relative.parts,
            'Unsafe relative package path: ' + str(relative))
    result = root / relative
    require(result.resolve().is_relative_to(root), 'Path escapes package: ' + str(result))
    return result


def check_hash(path, expected, label):
    require(path.is_file(), 'Missing ' + label + ': ' + str(path))
    actual = sha_file(path)
    require(actual == expected, 'Changed ' + label + ': ' + str(path))
    return actual


def keyed(rows, key, label):
    result = {}
    for row in rows:
        name = row[key]
        require(name not in result, 'Duplicate ' + label + ': ' + name)
        result[name] = row
    return result


def load_baseline():
    check_hash(BASELINE_PATH, BASELINE_SHA256, 'immutable foundation baseline')
    baseline = json_file(BASELINE_PATH)
    require(baseline['schema'] == 'hmt.foundation.baseline.v1', 'Unsupported baseline schema')
    require(len(baseline['modules']) == 122, 'Baseline must retain exactly 122 modules')
    require(set(baseline['allowed_axioms']) == ALLOWED_AXIOMS, 'Changed axiom policy')
    return baseline


def load_verifier(package, baseline):
    """Import only the hash-bound pure planner, never the auto-running wrapper."""
    info = baseline['verifier']
    path = safe_child(package, info['path'])
    raw = path.read_bytes()
    require(sha_bytes(raw) == info['sha256'], 'Changed source planner: ' + str(path))
    verifier = types.ModuleType('foundation_bound_planner')
    verifier.__file__ = str(path)
    # Execute exactly the checked bytes; a timestamp-valid .pyc is not evidence.
    exec(compile(raw, str(path), 'exec'), verifier.__dict__)
    verifier.SOURCE_ROOTS = tuple(baseline['source_roots'])
    verifier.MANDATORY_MODULES = tuple(
        n for n in baseline['focal_modules'] if n != verifier.OPTIONAL_MODULE)
    return verifier


def check_active_bindings(package, baseline, plan, receipt):
    """Shared real/negative-test precontrol: names, variants, imports and bytes."""
    wanted = baseline['modules']
    require(set(plan['graph']) == set(wanted), 'Active module set changed or missing')
    require(plan['compile_order'] == baseline['compile_order'], 'Import closure/order changed')
    manifest = json_file(package / 'MANIFIESTO.json')
    entries = keyed(manifest['files'], 'path', 'manifest path')
    for relative in entries:
        safe_child(package, relative)
    sources = keyed(receipt['sources'], 'module', 'receipt source name')
    objects = keyed(receipt['modules'], 'module', 'receipt object name')
    require(set(sources) == set(objects) == set(wanted), 'Receipt module set changed')
    build = safe_child(package, baseline['build_path'])
    require(build.is_dir(), 'Missing validated object directory')
    inventory = {'.'.join(p.relative_to(build).with_suffix('').parts)
                 for p in build.rglob('*.olean')}
    require(inventory == set(wanted), 'Object inventory changed or missing (shadow objects rejected)')
    for module, expected in wanted.items():
        node, source, obj = plan['graph'][module], sources[module], objects[module]
        require(node['sha256'] == expected['source_sha256'], 'Active variant changed: ' + module)
        require(node['path'] == expected['path'], 'Active source path changed: ' + module)
        require(node['imports'] == expected['imports'], 'Active imports changed: ' + module)
        require(node['path'] in entries, 'Active source absent from manifest: ' + module)
        require(entries[node['path']]['sha256'] == expected['source_sha256'],
                'Manifest variant changed: ' + module)
        check_hash(safe_child(package, node['path']), expected['source_sha256'], 'source ' + module)
        require(source == dict(module=module, path=expected['path'],
                               sha256=expected['source_sha256'], imports=expected['imports']),
                'Receipt source binding changed: ' + module)
        require(obj['source'] == expected['path'] and
                obj['source_sha256'] == expected['source_sha256'] and
                obj['object_sha256'] == expected['object_sha256'] and obj['exit_code'] == 0,
                'Receipt object binding changed: ' + module)
        require(set(obj['dependencies']) == set(expected['imports']),
                'Receipt dependency names changed: ' + module)
        for dependency, value in obj['dependencies'].items():
            digest = (wanted[dependency]['object_sha256'] if dependency in wanted
                      else baseline['external_objects'][dependency])
            require(value['object_sha256'] == digest,
                    'Receipt dependency object changed: ' + module + ' -> ' + dependency)
        relative = Path(*module.split('.')).with_suffix('.olean')
        check_hash(safe_child(package, Path(baseline['build_path']) / relative),
                   expected['object_sha256'], 'object ' + module)
    return dict(status='PASS_FIXED_SOURCE_OBJECT_BINDINGS', module_count=len(wanted),
                source_hashes_checked=len(wanted), object_hashes_checked=len(wanted),
                exact_active_variants=True, imports_checked=True,
                manifest_sha256=sha_file(package / 'MANIFIESTO.json'))


def precontrol(package, baseline):
    for label in ('receipt', 'source_manifest', 'wrapper', 'verifier'):
        info = baseline[label]
        check_hash(safe_child(package, info['path']), info['sha256'], label)
    receipt = json_file(package / baseline['receipt']['path'])
    require(receipt['status'] == baseline['receipt']['status'], 'Source receipt was not PASS')
    require(receipt['manifest_sha256'] == baseline['source_manifest']['sha256'],
            'Receipt does not bind the preserved historical source manifest')
    require(receipt['compiler'] == baseline['compiler'], 'Receipt compiler identity changed')
    require(receipt['local_module_count'] == len(baseline['modules']), 'Receipt count changed')
    require(receipt['compile_order'] == baseline['compile_order'], 'Receipt import order changed')
    require({n: r['object_sha256'] for n, r in receipt['external_objects'].items()}
            == baseline['external_objects'], 'Receipt external bindings changed')
    verifier = load_verifier(package, baseline)
    plan = verifier.load_plan(package)
    require(plan['focal_modules'] == baseline['focal_modules'], 'Focal module selection changed')
    require(not plan['optional_unmanifested_ignored'], 'An active optional variant is unmanifested')
    require(set(plan['external_modules']) == set(baseline['external_objects']),
            'External import set changed')
    checks = check_active_bindings(package, baseline, plan, receipt)
    entries = keyed(json_file(package / 'MANIFIESTO.json')['files'], 'path', 'manifest path')
    for label in ('receipt', 'source_manifest', 'wrapper', 'verifier'):
        info = baseline[label]
        require(info['path'] in entries and entries[info['path']]['sha256'] == info['sha256'],
                'Manifest omits/changes pinned ' + label)
    return verifier, checks


def run(command, cwd, env=None, timeout=600):
    try:
        result = subprocess.run(command, cwd=cwd, env=env, text=True, capture_output=True,
                                timeout=timeout)
        return result.returncode, result.stdout + result.stderr
    except subprocess.TimeoutExpired as error:
        def decoded(value):
            return value.decode(errors='replace') if isinstance(value, bytes) else (value or '')
        return 124, decoded(error.stdout) + decoded(error.stderr) + '\nTIMEOUT\n'


def checked(command, cwd):
    code, output = run(command, cwd, timeout=30)
    require(code == 0, f'Command failed ({code}): {command!r}\n{output}')
    return output.strip()


def runtime(lean_argument, mathlib, baseline):
    found = shutil.which(lean_argument)
    require(found is not None, 'Lean executable not found: ' + lean_argument)
    prefix = Path(checked([found, '--print-prefix'], mathlib)).resolve()
    lean = prefix / 'bin' / 'lean'
    check_hash(lean, baseline['compiler']['binary_sha256'], 'accepted Lean binary')
    version = checked([str(lean), '--version'], mathlib)
    require(version == baseline['compiler']['version'], 'Lean version/platform changed: ' + version)
    commit = checked(['git', 'rev-parse', 'HEAD'], mathlib)
    require(commit == baseline['compiler']['mathlib_commit'], 'Mathlib revision changed: ' + commit)
    paths = [safe_child(mathlib, p) for p in baseline['mathlib_search_paths']]
    paths.append(prefix / 'lib' / 'lean')
    # Lake may list empty package-library paths (e.g. Cli). Only dependencies
    # actually resolved below must exist; no library is built to fill a gap.
    external = {}
    for module, digest in baseline['external_objects'].items():
        relative = Path(*module.split('.')).with_suffix('.olean')
        file = next((p / relative for p in paths if (p / relative).is_file()), None)
        require(file is not None, 'Missing external object: ' + module)
        check_hash(file, digest, 'direct external object ' + module)
        external[module] = dict(path=str(file), object_sha256=digest)
    return dict(executable=str(lean), binary_sha256=sha_file(lean), version=version,
                mathlib_commit=commit, external_objects=external,
                library_paths=[str(p) for p in paths])


def parse_axioms(output, expected):
    reports = {}
    pattern = r"'([^'\r\n]+)'\s+depends\s+on\s+axioms:\s*\[([^\]]*)\]"
    for match in re.finditer(pattern, output):
        name = match.group(1)
        require(name not in reports, 'Duplicate axiom report: ' + name)
        reports[name] = sorted(a.strip() for a in match.group(2).split(',') if a.strip())
    for match in re.finditer(r"'([^'\r\n]+)'\s+does not depend on any axioms", output):
        require(match.group(1) not in reports, 'Duplicate axiom report: ' + match.group(1))
        reports[match.group(1)] = []
    require(not re.search(r'\bsorryAx\b', output), 'Forbidden sorryAx in Lean output')
    unexpected = {a for values in reports.values() for a in values} - ALLOWED_AXIOMS
    require(not unexpected, 'Non-standard axiom(s): ' + ', '.join(sorted(unexpected)))
    require(set(reports) == set(expected), 'Missing or unexpected named axiom report')
    return reports


def check_contract_digest(data):
    require(sha_bytes(data) == CONTRACT_SHA256,
            'Changed frozen foundation contract; explicit review is required, not automatic recapture')


def inspect_contract(verifier, data):
    check_contract_digest(data)
    imports, count = verifier.inspect_source(data, 'FoundationRegression.lean')
    require(imports == CONTRACT_IMPORTS, 'Foundation contract imports changed')
    code = verifier.mask_comments_strings(data.decode('utf-8'))
    queries = re.findall(r'^\s*#print\s+axioms\s+(\S+)\s*$', code, re.M)
    require(len(queries) == count == len(EXPECTED_QUERIES) and set(queries) == EXPECTED_QUERIES,
            'Foundation contract must retain the 19 explicit named axiom queries')


def write_json(path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


def self_test():
    """Exercise the actual binding checker without using/altering the package."""
    load_baseline()
    results = [dict(test='immutable_baseline_digest_matches', status='PASS')]
    accepted_contract = (HERE / 'FoundationRegression.lean').read_bytes()
    check_contract_digest(accepted_contract)
    results.append(dict(test='frozen_contract_digest_matches', status='PASS'))
    try:
        check_contract_digest(accepted_contract + b'\n-- changed candidate\n')
    except ContractFailure as error:
        results.append(dict(test='changed_contract_rejected', status='PASS', detected=str(error)))
    else:
        raise ContractFailure('Modified contract digest incorrectly accepted')
    with tempfile.TemporaryDirectory(prefix='hmt-foundation-selftest-') as temporary:
        root = Path(temporary).resolve()
        source = root / 'sources' / 'A.lean'
        source.parent.mkdir()
        build = root / 'build'
        build.mkdir()
        target = build / 'A.olean'
        original, compiled = b'def stable : Nat := 1\n', b'fixture-object-not-lean\n'
        original_hash, object_hash = sha_bytes(original), sha_bytes(compiled)
        baseline = dict(modules={'A': dict(path='sources/A.lean', source_sha256=original_hash,
                                          imports=[], object_sha256=object_hash)},
                        compile_order=['A'], build_path='build', external_objects={})
        plan = dict(graph={'A': dict(path='sources/A.lean', sha256=original_hash, imports=[])},
                    compile_order=['A'])
        receipt = dict(sources=[dict(module='A', path='sources/A.lean', sha256=original_hash,
                                    imports=[])], modules=[dict(module='A', source='sources/A.lean',
                                    source_sha256=original_hash, object_sha256=object_hash,
                                    exit_code=0, dependencies={})])

        def reset():
            source.write_bytes(original)
            target.write_bytes(compiled)
            plan['graph']['A'] = dict(path='sources/A.lean', sha256=original_hash, imports=[])
            write_json(root / 'MANIFIESTO.json',
                       {'files': [dict(path='sources/A.lean', sha256=original_hash)]})

        def check():
            return check_active_bindings(root, baseline, plan, receipt)

        def reject(name, action, expected):
            reset()
            action()
            try:
                check()
            except ContractFailure as error:
                require(expected in str(error), f'{name}: wrong failure: {error}')
                results.append(dict(test=name, status='PASS', detected=str(error)))
            else:
                raise ContractFailure('Negative self-test incorrectly accepted: ' + name)

        reset()
        check()
        results.append(dict(test='unchanged_fixture_accepted', status='PASS'))
        reject('module_changed', lambda: source.write_bytes(b'def stable : Nat := 2\n'),
               'Changed source')
        reject('module_missing', source.unlink, 'Missing source')

        def change_active_alias():
            new = b'def stable : Nat := 3\n'
            source.write_bytes(new)
            (source.parent / 'A_original.lean').write_bytes(original)
            plan['graph']['A']['sha256'] = sha_bytes(new)
            write_json(root / 'MANIFIESTO.json', {'files': [
                dict(path='sources/A.lean', sha256=sha_bytes(new)),
                dict(path='sources/A_original.lean', sha256=original_hash)]})

        reject('active_alias_changed_with_updated_manifest_and_retained_original',
               change_active_alias, 'Active variant changed')
        reject('object_altered', lambda: target.write_bytes(b'wrong-object'), 'Changed object')
        reject('object_missing', target.unlink, 'Object inventory changed')
        reject('imports_altered', lambda: plan['graph']['A'].update(imports=['Other']),
               'Active imports changed')
        reject('module_removed_from_plan', lambda: plan['graph'].pop('A'), 'Active module set changed')
    accepted = "'P' depends on axioms: [propext, Classical.choice, Quot.sound, Lean.ofReduceBool]"
    parse_axioms(accepted, {'P'})
    results.append(dict(test='standard_and_native_axioms_accepted', status='PASS'))
    for name, output, expected in (
        ('sorryAx_rejected', "'P' depends on axioms: [sorryAx]", 'Forbidden sorryAx'),
        ('own_axiom_rejected', "'P' depends on axioms: [My.axiom]", 'Non-standard axiom'),
        ('missing_report_rejected', '', 'Missing or unexpected'),
    ):
        try:
            parse_axioms(output, {'P'})
        except ContractFailure as error:
            require(expected in str(error), f'{name}: wrong failure: {error}')
            results.append(dict(test=name, status='PASS', detected=str(error)))
        else:
            raise ContractFailure('Negative axiom test incorrectly accepted: ' + name)
    return dict(status='PASS_FOUNDATION_RUNNER_SELF_TESTS', compiler_invoked=False,
                package_modified=False, tests=results, test_count=len(results))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--package', type=Path, help='Accepted shared-base package (read-only)')
    parser.add_argument('--lean', default='lean', help='Accepted Lean 4.21.0 executable')
    parser.add_argument('--mathlib', type=Path, help='Existing precompiled Mathlib checkout')
    parser.add_argument('--output', type=Path, help='New/empty output directory outside the package')
    parser.add_argument('--self-test', action='store_true', help='Run fixture tests only; no compiler')
    args = parser.parse_args()
    if args.self_test:
        try:
            result = self_test()
            print(json.dumps(result, ensure_ascii=False, indent=2))
            return 0
        except Exception as error:
            print(json.dumps(dict(status='FAIL_SELF_TEST', error=str(error)), ensure_ascii=False))
            return 1
    if args.package is None or args.mathlib is None or args.output is None:
        parser.error('--package, --mathlib and --output are required without --self-test')
    report = dict(schema='hmt.foundation.regression.v1', status='RUNNING',
                  started_at_utc=datetime.now(timezone.utc).isoformat(), invocation=sys.argv,
                  upstream_modules_compiled=0, mathlib_rebuilt=False, package_modified=False,
                  whole_pdf_formalized=False, allowed_axioms=sorted(ALLOWED_AXIOMS),
                  limits=['Reuses the accepted 122 object files; does not recompile upstream.',
                          'Pins direct external objects, not every transitive Mathlib/runtime artifact.',
                          'Lean.ofReduceBool is permitted: this is not a kernel-only reduction claim.',
                          'Contract scope and its existing S8/X/Y interfaces are unchanged.'])
    output = None
    try:
        package, mathlib = args.package.expanduser().resolve(), args.mathlib.expanduser().resolve()
        requested = args.output.expanduser().resolve()
        require(package.is_dir() and mathlib.is_dir(), 'Package and Mathlib directories must exist')
        require(not requested.is_relative_to(package) and not package.is_relative_to(requested),
                'Output must be outside and not an ancestor of the sealed package')
        require(not requested.is_relative_to(mathlib) and not mathlib.is_relative_to(requested),
                'Output must be outside and not an ancestor of Mathlib')
        require(not requested.exists() or (requested.is_dir() and not any(requested.iterdir())),
                'Output directory must be new or empty (previous evidence is never overwritten)')
        requested.mkdir(parents=True, exist_ok=True)
        output = requested
        baseline = load_baseline()
        report.update(package=str(package), baseline_sha256=BASELINE_SHA256,
                      accepted_contract_sha256=CONTRACT_SHA256,
                      runner_sha256=sha_file(Path(__file__)), source_receipt=baseline['receipt'],
                      source_manifest=baseline['source_manifest'])
        verifier, checks = precontrol(package, baseline)
        report['precontrol'] = checks
        active_runtime = runtime(args.lean, mathlib, baseline)
        report['runtime'] = active_runtime
        contract = HERE / 'FoundationRegression.lean'
        raw = contract.read_bytes()
        inspect_contract(verifier, raw)
        contract_hash = sha_bytes(raw)
        build = output / 'build'
        build.mkdir()
        snapshot, target = build / 'FoundationRegression.lean', build / 'FoundationRegression.olean'
        snapshot.write_bytes(raw)
        paths = [build, package / baseline['build_path'], *active_runtime['library_paths']]
        env = dict(os.environ, LEAN_PATH=os.pathsep.join(map(str, paths)))
        command = [active_runtime['executable'], '-DwarningAsError=true', '--root=' + str(build),
                   '-o', str(target), str(snapshot)]
        report['compilation'] = dict(module='FoundationRegression', command=command,
                                     source_sha256=contract_hash, lean_path=env['LEAN_PATH'])
        code, log = run(command, mathlib, env)
        log_path = output / 'FoundationRegression.log'
        log_path.write_text(log, encoding='utf-8')
        report['compilation'].update(exit_code=code, log=str(log_path), log_sha256=sha_file(log_path))
        require(code == 0, f'FoundationRegression compilation failed ({code}); inspect {log_path}')
        reports = parse_axioms(log, EXPECTED_QUERIES)
        require(target.is_file(), 'Compiler returned success without its object')
        report['compilation']['object_sha256'] = sha_file(target)
        report.update(axiom_reports=reports, axiom_report_count=len(reports),
                      axioms=sorted({a for values in reports.values() for a in values}))
        check_hash(contract, contract_hash, 'foundation contract during compilation')
        check_hash(snapshot, contract_hash, 'compiled foundation snapshot')
        load_baseline()
        _, after = precontrol(package, baseline)
        require(after == checks, 'Package bindings/manifest changed during contract compilation')
        require(runtime(args.lean, mathlib, baseline) == active_runtime,
                'Runtime changed during contract compilation')
        check_hash(Path(__file__), report['runner_sha256'], 'runner during contract compilation')
        report.update(status='PASS_FOUNDATION_CONTRACT', compiled_modules=['FoundationRegression'])
        code = 0
    except Exception as error:
        report.update(status='FAIL_FOUNDATION_CONTRACT', error_type=type(error).__name__, error=str(error))
        code = 1
    report['finished_at_utc'] = datetime.now(timezone.utc).isoformat()
    if output is not None:
        write_json(output / 'VERIFICATION.json', report)
    print(json.dumps(report, ensure_ascii=False, indent=2), flush=True)
    return code


if __name__ == '__main__':
    raise SystemExit(main())
