#!/usr/bin/env python3
"""Joint thermal/geometric curve, using existing HMT outputs only."""
from pathlib import Path
from fractions import Fraction as F
import json
import hashlib
import mpmath as mp

ROOT = Path(__file__).resolve().parent
BASE = ROOT.parents[1] / 'BEKENSTEIN_HAWKING_COMPOSICION_HMT_20260928'
SRC = BASE/'DELTA_01_SUSTITUCION_TOTAL/RESULTADOS_SUSTITUCION.json'
PEER = ROOT.parent/'aclarar/RESULTADOS.json'
raw = json.loads(SRC.read_text())
peer = json.loads(PEER.read_text())
pi_path = ROOT.parents[1] / 'entradas/pi_1000_decimales.txt'
assert hashlib.sha256(pi_path.read_bytes()).hexdigest() == raw['upstream_coordinates']['pi']['sha256']
mp.mp.dps = 100
pi = mp.mpf(pi_path.read_text().strip())
values = {k: mp.mpf(v) for k,v in raw['values'].items()}
a, eta, H5 = values['alpha'], values['eta_ret'], values['H5']
fpi = 1-7*pi/8748
scale = 50*pi*fpi*a/243
checks = []

def check(name, condition, kind='decimal_100'):
    checks.append(dict(name=name, passed=bool(condition), kind=kind))
    if not condition: raise AssertionError(name)

def close(name, x, y, tol=mp.mpf('1e-57')):
    check(name, abs(x-y) < tol*max(1,abs(x),abs(y)))

# Symbolic coefficient elimination tested in exact rational arithmetic;
# these are witnesses for the identity, not alternative generated constants.
for ar, er, pr in [(F(1,100),F(1),F(7,3)), (F(2,17),F(3,5),F(2)), (F(3,1000),F(7,6),F(11,7))]:
    dr = pr*(499*ar-er)/2430
    xr = (er+ar)/(500*ar)
    sr = 50*pr*ar/243
    check('rational_elimination_'+str(ar), dr == sr*(1-xr), 'rational_exact')

def readings(action):
    xi = (action+a)/(500*a)
    s = mp.atanh(xi)
    d = pi*fpi*(499*a-action)/2430
    z = (1-mp.sqrt(1-xi*xi))/(1+mp.sqrt(1-xi*xi))
    omega = 2*mp.atan(mp.sqrt(3)*z/(2-z))
    contrast = mp.sqrt(3)*z*(2-z)/(2*(1-z+z*z))
    radius = mp.acosh(1+mp.sinh(s)**2/2)
    success = mp.exp(-2*s-radius)
    C = 1000*a*xi
    qm = mp.exp(-27*d/fpi)
    qp = mp.exp(-100*pi*a/9)/qm
    Sm = lambda q,m: q**m/(1-q**(3*m))
    gamma = pi*1000*a*C/180+12*(Sm(qm,90)-Sm(qp,90))-(Sm(qm,120)-Sm(qp,120))
    a0 = (1+2*mp.cos(pi/18))/3*pi*C/1080
    return dict(xi=xi,s=s,d=d,z=z,omega=omega,contrast=contrast,r=radius,
                success=success,contrast_per_input=success*contrast,gamma=gamma,a0=a0,
                q_minus=qm,q_plus=qp,C_deg=C,eta_recovered=499*a-2430*d/(pi*fpi))

ret = readings(eta)
pre = readings(H5)
for label,r in [('ret',ret),('pre',pre)]:
    close(label+'_elimination',r['d'],scale*(1-r['xi']))
    close(label+'_rapidity',r['d'],scale*(1-mp.tanh(r['s'])))
    close(label+'_sine',r['contrast'],mp.sin(r['omega']))
    close(label+'_half_angle',r['z'],mp.tanh(r['s']/2)**2)
    close(label+'_channel_minus',r['q_minus'],mp.exp(-pi*(1000*a-r['C_deg'])/180))
    close(label+'_channel_plus',r['q_plus'],mp.exp(-pi*(1000*a+r['C_deg'])/180))
    check(label+'_domain',mp.mpf(1)/500<r['xi']<1 and 0<r['d']<499*scale/500 and 0<r['success']<1)
for key,source_key in [('d','d'),('gamma','gamma'),('a0','a0'),('C_deg','C_deg'),('q_minus','q_minus')]:
    close('prior_'+key,ret[key],values[source_key])
close('recover_action_ret',ret['eta_recovered'],eta)
close('recover_action_pre',pre['eta_recovered'],H5)
for key,pkey in [('s','s'),('omega','omega_rad'),('contrast','spin_contrast_conditional'),('success','success_probability'),('contrast_per_input','spin_contrast_per_input')]:
    close('peer_'+key,ret[key],mp.mpf(peer['values'][pkey]),mp.mpf('1e-43'))

# Every thermal likelihood ratio gives the same reconstructed d, without
# using mean energy or a radius. Distribution is generated by inherited d.
g=[1]
for _ in range(18):
    nxt=[0]*(len(g)+2)
    for k,v in enumerate(g):
        for j in range(3): nxt[k+j]+=v
    g=nxt
d=ret['d']
Z=(1+mp.exp(-3*d)+mp.exp(-6*d))**18*(1+mp.exp(-4*d)+mp.exp(-8*d))**18
law={m:mp.mpf(0) for m in range(-36,37)}
for x in range(37):
    for y in range(37):
        law[x-y]+=g[x]*g[y]*mp.exp(-d*(3*x+4*y))/Z
for m in range(1,37):
    inferred=mp.log(law[m]/law[-m])/m
    close('probability_restitution_'+str(m),inferred,d)
    close('xi_restitution_'+str(m),1-inferred/scale,ret['xi'])

check('return_increases_d',ret['d']>pre['d'])
check('return_decreases_spin_contrast',ret['contrast']<pre['contrast'])
out=dict(status='PASS_JOINT_THERMAL_GEOMETRIC_CURVE', checks_count=len(checks),checks=checks,
         sources=[dict(path=str(p),sha256=hashlib.sha256(p.read_bytes()).hexdigest()) for p in [SRC,PEER,pi_path]],
         d_star=mp.nstr(scale,65),values={k:mp.nstr(v,65) for k,v in ret.items()},
         return_changes={k:mp.nstr(ret[k]-pre[k],50) for k in ['xi','s','d','omega','contrast','success','gamma','a0']},
         probability_ratio_M1=mp.nstr(mp.exp(d),65),
         numerical_policy='100-digit arithmetic on inherited finite precision outputs; no interval certification. Exact identity is proved algebraically in CURVA_TERMICA_GEOMETRICA.md.',
         scope='Posterior compatibility of declared thermal and electronic protocols. No experimental confirmation or adjustable generated constants is claimed.')
(ROOT/'RESULTADOS_CURVA.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
print(out['status'],len(checks),'checks; d_star=',out['d_star'])
