import LatticeFiniteRepresentation
import LatticeFiniteIrreducible
import LatticeFiniteCharacter
import LatticeFiniteDimension
import LatticeFiniteGroundState
import LatticeTwistedOscillatorTensor
import LatticeTwistedCarrier
import LatticeTwistedParity
import LatticeTwistedPositiveSector
import LatticeHalfWeightBasis
import LatticeTwistedLowWeights
import LatticeOrbifoldCarrier
import LatticeTwistedGrading
import LatticeTwistedBasisParity
import LatticeTwistedPositiveGrading
import LatticeOrbifoldGrading
import LatticeTwistedWeightTwo
#print axioms HMT.IV.LatticeFiniteRepresentation.complexSign
#print axioms HMT.IV.LatticeFiniteRepresentation.complexSign_zero
#print axioms HMT.IV.LatticeFiniteRepresentation.complexSign_one
#print axioms HMT.IV.LatticeFiniteRepresentation.complexSign_add
#print axioms HMT.IV.LatticeFiniteRepresentation.complexSign_sq
#print axioms HMT.IV.LatticeFiniteRepresentation.RegularSpace
#print axioms HMT.IV.LatticeFiniteRepresentation.finiteAction
#print axioms HMT.IV.LatticeFiniteRepresentation.finiteAction_apply
#print axioms HMT.IV.LatticeFiniteRepresentation.finiteAction_one
#print axioms HMT.IV.LatticeFiniteRepresentation.finiteAction_mul
#print axioms HMT.IV.LatticeFiniteRepresentation.finiteRepresentation
#print axioms HMT.IV.LatticeFiniteRepresentation.finiteAction_center
#print axioms HMT.IV.LatticeFiniteRepresentation.central_involution_negative
#print axioms HMT.IV.LatticeFiniteRepresentation.regularSpace_finrank
#print axioms HMT.IV.LatticeFiniteIrreducible.GroupAlgebra
#print axioms HMT.IV.LatticeFiniteIrreducible.RegularModule
#print axioms HMT.IV.LatticeFiniteIrreducible.regularModule_addCommGroup
#print axioms HMT.IV.LatticeFiniteIrreducible.regularModule_nontrivial
#print axioms HMT.IV.LatticeFiniteIrreducible.regularModule_finite
#print axioms HMT.IV.LatticeFiniteIrreducible.simple_constituent_exists
#print axioms HMT.IV.LatticeFiniteIrreducible.simpleConstituent
#print axioms HMT.IV.LatticeFiniteIrreducible.simpleConstituent_simple
#print axioms HMT.IV.LatticeFiniteIrreducible.FiniteSpace
#print axioms HMT.IV.LatticeFiniteIrreducible.finiteSpace_nontrivial
#print axioms HMT.IV.LatticeFiniteIrreducible.finiteSpace_finite
#print axioms HMT.IV.LatticeFiniteIrreducible.constituentRepresentation
#print axioms HMT.IV.LatticeFiniteIrreducible.inclusion
#print axioms HMT.IV.LatticeFiniteIrreducible.inclusion_injective
#print axioms HMT.IV.LatticeFiniteIrreducible.inclusion_intertwines
#print axioms HMT.IV.LatticeFiniteIrreducible.constituent_center
#print axioms HMT.IV.LatticeFiniteIrreducible.constituent_central_involution_negative
#print axioms HMT.IV.LatticeFiniteIrreducible.finiteFDRep
#print axioms HMT.IV.LatticeFiniteIrreducible.constituentModuleEquiv
#print axioms HMT.IV.LatticeFiniteIrreducible.constituent_asModule_simple
#print axioms HMT.IV.LatticeFiniteIrreducible.finiteFDRep_simple
#print axioms HMT.IV.LatticeFiniteCharacter.centralElement
#print axioms HMT.IV.LatticeFiniteCharacter.parityLift
#print axioms HMT.IV.LatticeFiniteCharacter.exists_pairing_one
#print axioms HMT.IV.LatticeFiniteCharacter.conjugate_to_central_negative
#print axioms HMT.IV.LatticeFiniteCharacter.character_off_center
#print axioms HMT.IV.LatticeFiniteCharacter.character_center
#print axioms HMT.IV.LatticeFiniteCharacter.character_formula
#print axioms HMT.IV.LatticeFiniteCharacter.central_inverse
#print axioms HMT.IV.LatticeFiniteCharacter.character_pair_sum
#print axioms HMT.IV.LatticeFiniteDimension.irreducible_dimension
#print axioms HMT.IV.LatticeFiniteDimension.irreducible_unique
#print axioms HMT.IV.LatticeFiniteGroundState.finiteSpace_dimension
#print axioms HMT.IV.LatticeFiniteGroundState.finiteSpace_unique
#print axioms HMT.IV.LatticeFiniteGroundState.parityOperator
#print axioms HMT.IV.LatticeFiniteGroundState.parityOperator_zero
#print axioms HMT.IV.LatticeFiniteGroundState.parityOperator_product
#print axioms HMT.IV.LatticeFiniteGroundState.latticeOperator
#print axioms HMT.IV.LatticeFiniteGroundState.latticeOperator_product
#print axioms HMT.IV.LatticeFiniteGroundState.latticeOperator_neg
#print axioms HMT.IV.LatticeFiniteGroundState.latticeOperator_zero
#print axioms HMT.IV.LatticeFiniteGroundState.latticeOperator_two_periodic
#print axioms HMT.IV.LatticeFiniteGroundState.extensionRepresentation
#print axioms HMT.IV.LatticeFiniteGroundState.extensionRepresentation_theta
#print axioms HMT.IV.LatticeFiniteGroundState.displacement_acts_trivially
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.TensorFock
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.halfModeTensor
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.conformalModeTensor
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.halfModeTensor_tmul
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.conformalModeTensor_tmul
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.half_heisenberg_tensor
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.virasoro_tensor
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.virasoro_tensor_central_charge_twentyFour
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.vacuum_tensor_weight
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.vacuum_tensor_annihilation
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.secondFactorOperator
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.tensor_factors_commute
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.halfModeTensor_comm_second
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.conformalModeTensor_comm_second
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.secondFactorAction
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.secondFactorAction_comm_half
#print axioms HMT.IV.LatticeTwistedOscillatorTensor.secondFactorAction_comm_conformal
#print axioms HMT.IV.LatticeTwistedCarrier.Carrier
#print axioms HMT.IV.LatticeTwistedCarrier.carrierAddCommGroup
#print axioms HMT.IV.LatticeTwistedCarrier.carrierModule
#print axioms HMT.IV.LatticeTwistedCarrier.groundEmbedding
#print axioms HMT.IV.LatticeTwistedCarrier.groundProjection
#print axioms HMT.IV.LatticeTwistedCarrier.ground_projection_embedding
#print axioms HMT.IV.LatticeTwistedCarrier.groundEmbedding_injective
#print axioms HMT.IV.LatticeTwistedCarrier.groundSubspace
#print axioms HMT.IV.LatticeTwistedCarrier.groundSubspace_dimension
#print axioms HMT.IV.LatticeTwistedCarrier.halfMode
#print axioms HMT.IV.LatticeTwistedCarrier.conformalMode
#print axioms HMT.IV.LatticeTwistedCarrier.chargeOperator
#print axioms HMT.IV.LatticeTwistedCarrier.chargeOperator_product
#print axioms HMT.IV.LatticeTwistedCarrier.chargeOperator_neg
#print axioms HMT.IV.LatticeTwistedCarrier.chargeOperator_comm_half
#print axioms HMT.IV.LatticeTwistedCarrier.chargeOperator_comm_conformal
#print axioms HMT.IV.LatticeTwistedCarrier.ground_weight
#print axioms HMT.IV.LatticeTwistedCarrier.ground_annihilated
#print axioms HMT.IV.LatticeTwistedCarrier.virasoro_central_charge_twentyFour
#print axioms HMT.IV.LatticeTwistedParity.liftedTheta
#print axioms HMT.IV.LatticeTwistedParity.liftedTheta_tmul
#print axioms HMT.IV.LatticeTwistedParity.liftedTheta_square
#print axioms HMT.IV.LatticeTwistedParity.evenProjector
#print axioms HMT.IV.LatticeTwistedParity.oddProjector
#print axioms HMT.IV.LatticeTwistedParity.even_fixed
#print axioms HMT.IV.LatticeTwistedParity.odd_negated
#print axioms HMT.IV.LatticeTwistedParity.parity_decomposition
#print axioms HMT.IV.LatticeTwistedParity.even_idempotent
#print axioms HMT.IV.LatticeTwistedParity.odd_idempotent
#print axioms HMT.IV.LatticeTwistedParity.even_odd_zero
#print axioms HMT.IV.LatticeTwistedParity.odd_even_zero
#print axioms HMT.IV.LatticeTwistedParity.liftedTheta_ground
#print axioms HMT.IV.LatticeTwistedParity.even_ground_zero
#print axioms HMT.IV.LatticeTwistedParity.odd_ground_identity
#print axioms HMT.IV.LatticeTwistedParity.theta_create
#print axioms HMT.IV.LatticeTwistedParity.theta_halfAnnihilate
#print axioms HMT.IV.LatticeTwistedParity.theta_halfMode
#print axioms HMT.IV.LatticeTwistedParity.liftedTheta_halfMode
#print axioms HMT.IV.LatticeTwistedParity.first_oscillator_positive
#print axioms HMT.IV.LatticeTwistedParity.even_first_oscillator_identity
#print axioms HMT.IV.LatticeTwistedParity.liftedTheta_comm_charge
#print axioms HMT.IV.LatticeTwistedParity.theta_creationHalfTerm
#print axioms HMT.IV.LatticeTwistedParity.theta_annihilationHalfTerm
#print axioms HMT.IV.LatticeTwistedParity.theta_halfNormalMode
#print axioms HMT.IV.LatticeTwistedParity.theta_quadraticMode
#print axioms HMT.IV.LatticeTwistedParity.theta_shiftedModes
#print axioms HMT.IV.LatticeTwistedParity.liftedTheta_comm_conformal_apply
#print axioms HMT.IV.LatticeTwistedParity.liftedTheta_comm_conformal
#print axioms HMT.IV.LatticeTwistedPositiveSector.positiveSector
#print axioms HMT.IV.LatticeTwistedPositiveSector.mem_positiveSector
#print axioms HMT.IV.LatticeTwistedPositiveSector.evenProjector_fixed_identity
#print axioms HMT.IV.LatticeTwistedPositiveSector.positiveSector_eq_projector_range
#print axioms HMT.IV.LatticeTwistedPositiveSector.positiveRangeEquiv
#print axioms HMT.IV.LatticeTwistedPositiveSector.conformalMode_mem_positive
#print axioms HMT.IV.LatticeTwistedPositiveSector.positiveConformalMode
#print axioms HMT.IV.LatticeTwistedPositiveSector.positiveConformalMode_coe
#print axioms HMT.IV.LatticeTwistedPositiveSector.positive_virasoro_central_charge_twentyFour
#print axioms HMT.IV.LatticeTwistedPositiveSector.first_oscillator_mem_positive
#print axioms HMT.IV.LatticeTwistedPositiveSector.first_oscillator_ne_zero
#print axioms HMT.IV.LatticeTwistedPositiveSector.positiveSector_nonzero
#print axioms HMT.IV.LatticeTwistedPositiveSector.positiveSector_nontrivial
#print axioms HMT.IV.LatticeHalfWeightBasis.twiceWeight
#print axioms HMT.IV.LatticeHalfWeightBasis.twiceWeight_zero
#print axioms HMT.IV.LatticeHalfWeightBasis.twiceWeight_add
#print axioms HMT.IV.LatticeHalfWeightBasis.twiceWeight_single
#print axioms HMT.IV.LatticeHalfWeightBasis.quadratic_zero_create
#print axioms HMT.IV.LatticeHalfWeightBasis.quadratic_zero_monomial
#print axioms HMT.IV.LatticeHalfWeightBasis.shifted_zero_monomial
#print axioms HMT.IV.LatticeTwistedLowWeights.finiteBasis
#print axioms HMT.IV.LatticeTwistedLowWeights.BasisIndex
#print axioms HMT.IV.LatticeTwistedLowWeights.twistedBasis
#print axioms HMT.IV.LatticeTwistedLowWeights.conformal_basis_weight
#print axioms HMT.IV.LatticeTwistedLowWeights.conformal_coefficient
#print axioms HMT.IV.LatticeTwistedLowWeights.low_weight_vector_zero
#print axioms HMT.IV.LatticeTwistedLowWeights.weight_zero_vanishes
#print axioms HMT.IV.LatticeTwistedLowWeights.weight_one_vanishes
#print axioms HMT.IV.LatticeOrbifoldCarrier.Space
#print axioms HMT.IV.LatticeOrbifoldCarrier.modes
#print axioms HMT.IV.LatticeOrbifoldCarrier.modes_apply
#print axioms HMT.IV.LatticeOrbifoldCarrier.vacuum
#print axioms HMT.IV.LatticeOrbifoldCarrier.conformalState
#print axioms HMT.IV.LatticeOrbifoldCarrier.virasoro_central_charge_twentyFour
#print axioms HMT.IV.LatticeOrbifoldCarrier.modes_vacuum
#print axioms HMT.IV.LatticeOrbifoldCarrier.modes_create_conformalState
#print axioms HMT.IV.LatticeOrbifoldCarrier.conformalState_weight_two
#print axioms HMT.IV.LatticeOrbifoldCarrier.eigenspace_components
#print axioms HMT.IV.LatticeOrbifoldCarrier.twisted_low_eigenvector_zero
#print axioms HMT.IV.LatticeOrbifoldCarrier.weight_one_zero
#print axioms HMT.IV.LatticeOrbifoldCarrier.weight_zero_vacuum_line
#print axioms HMT.IV.LatticeTwistedGrading.occupationWeight_le_twiceWeight
#print axioms HMT.IV.LatticeTwistedGrading.HalfOccupation
#print axioms HMT.IV.LatticeTwistedGrading.encodeOccupation
#print axioms HMT.IV.LatticeTwistedGrading.encodeOccupation_injective
#print axioms HMT.IV.LatticeTwistedGrading.halfOccupationFintype
#print axioms HMT.IV.LatticeTwistedGrading.WeightLabel
#print axioms HMT.IV.LatticeTwistedGrading.encodeLabel
#print axioms HMT.IV.LatticeTwistedGrading.encodeLabel_injective
#print axioms HMT.IV.LatticeTwistedGrading.weightLabelFintype
#print axioms HMT.IV.LatticeTwistedGrading.weightSpace
#print axioms HMT.IV.LatticeTwistedGrading.weightLabels_independent
#print axioms HMT.IV.LatticeTwistedGrading.weightBasis
#print axioms HMT.IV.LatticeTwistedGrading.weightBasis_coe
#print axioms HMT.IV.LatticeTwistedGrading.weightSpaceFinite
#print axioms HMT.IV.LatticeTwistedGrading.weightSpace_finrank
#print axioms HMT.IV.LatticeTwistedGrading.weightSpace_le_eigenspace
#print axioms HMT.IV.LatticeTwistedGrading.eigenspace_le_weightSpace
#print axioms HMT.IV.LatticeTwistedGrading.weightSpace_eq_eigenspace
#print axioms HMT.IV.LatticeTwistedGrading.conformal_eigenspace_finite
#print axioms HMT.IV.LatticeTwistedGrading.basis_mem_weight
#print axioms HMT.IV.LatticeTwistedGrading.weights_span
#print axioms HMT.IV.LatticeTwistedBasisParity.liftedTheta_basis
#print axioms HMT.IV.LatticeTwistedBasisParity.twiceWeight_mod_two
#print axioms HMT.IV.LatticeTwistedBasisParity.liftedTheta_coefficient
#print axioms HMT.IV.LatticeTwistedBasisParity.positive_basis_iff_odd
#print axioms HMT.IV.LatticeTwistedBasisParity.evenProjector_basis
#print axioms HMT.IV.LatticeTwistedBasisParity.positive_support_odd
#print axioms HMT.IV.LatticeTwistedBasisParity.odd_basis_integer_weight
#print axioms HMT.IV.LatticeTwistedBasisParity.positive_basis_integer_weight
#print axioms HMT.IV.LatticeTwistedBasisParity.positive_eigenvalue_integer_ge_two
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positiveWeightSpace
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positive_eigenspace_eq_comap
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positive_weight_zero
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positive_weight_one
#print axioms HMT.IV.LatticeTwistedPositiveGrading.integer_eigenspace_finite
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positiveWeightInclusion
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positiveWeightInclusion_injective
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positive_weight_finite
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positiveProjection
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positiveProjection_of_positive
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positiveProjection_mem_fixed_weight
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positive_weights_span
#print axioms HMT.IV.LatticeTwistedPositiveGrading.positive_eigenvalue_integer_ge_two
#print axioms HMT.IV.LatticeOrbifoldGrading.weightSpace
#print axioms HMT.IV.LatticeOrbifoldGrading.weightEquiv
#print axioms HMT.IV.LatticeOrbifoldGrading.weight_finite
#print axioms HMT.IV.LatticeOrbifoldGrading.weight_dimension
#print axioms HMT.IV.LatticeOrbifoldGrading.untwistedInclusion
#print axioms HMT.IV.LatticeOrbifoldGrading.twistedInclusion
#print axioms HMT.IV.LatticeOrbifoldGrading.untwisted_mem_weight
#print axioms HMT.IV.LatticeOrbifoldGrading.twisted_mem_weight
#print axioms HMT.IV.LatticeOrbifoldGrading.weights_span
#print axioms HMT.IV.LatticeOrbifoldGrading.assembled_graded_carrier
#print axioms HMT.IV.LatticeTwistedWeightTwo.twiceWeight_entry_le
#print axioms HMT.IV.LatticeTwistedWeightTwo.twiceWeight_zero_iff
#print axioms HMT.IV.LatticeTwistedWeightTwo.twiceWeight_one_iff
#print axioms HMT.IV.LatticeTwistedWeightTwo.firstWeightLabelEquiv
#print axioms HMT.IV.LatticeTwistedWeightTwo.firstWeightLabel_card
#print axioms HMT.IV.LatticeTwistedWeightTwo.firstWeightSpace_finrank
#print axioms HMT.IV.LatticeTwistedWeightTwo.firstWeightSpace_le_positive
#print axioms HMT.IV.LatticeTwistedWeightTwo.weight_two_eigenspace_eq
#print axioms HMT.IV.LatticeTwistedWeightTwo.positive_weight_two_eq_comap
#print axioms HMT.IV.LatticeTwistedWeightTwo.positive_weight_two_finrank
#print axioms HMT.IV.LatticeTwistedWeightTwo.positive_weight_two_dimension_product
