import ElectronReturn
import LedgerMassBridge

/-!
# Generated electronic ledger and the Article VI mass interface

This module composes two already verified pieces without replacing either of
them.  `ElectronReturn` produces the central 108-step electronic trajectory.
Before its later tritic publication, the positive nonadic residue at every
step is retained as a digit in `1,...,9`.  `LedgerSignature` then reads that
generated full ledger and `LedgerMassBridge` supplies the positive mass
operator.

No observed mass, target signature, metrological table or external route is
used to generate the ledger.  The five integers are computed from the full
chronological trajectory.  The theorem identifying them is a conclusion.
-/

namespace HMT.VI.ElectronGeneratedLedger

open HMT.VI.EventReconstruction
open HMT.VI.LedgerSignature
open HMT.VI.MassOperator
open HMT.VI.MassOperator.LedgerBridge
open HMTMassCharacter

set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

/-- The complete nonadic digit at a tick of the generated central electronic
trajectory, before the subsequent projection to its tritic publication. -/
def centralDigitalRoute : DigitalRoute := fun t =>
  let z := ElectronReturn.positiveRoot9
    (ElectronReturn.rawReading t.val (ElectronReturn.stateAt t.val))
  ⟨(z - 1).toNat, by
    have hz := ElectronReturn.positive_root_bounds
      (ElectronReturn.rawReading t.val (ElectronReturn.stateAt t.val))
    omega⟩

/-- `digitValue` recovers exactly the positive nonadic residue generated by
the central trajectory; the `Fin 9` encoding does not change the digit. -/
theorem central_digit_value (t : Fin 108) :
    digitValue (centralDigitalRoute t) =
      ElectronReturn.positiveRoot9
        (ElectronReturn.rawReading t.val (ElectronReturn.stateAt t.val)) := by
  have hz := ElectronReturn.positive_root_bounds
    (ElectronReturn.rawReading t.val (ElectronReturn.stateAt t.val))
  simp only [centralDigitalRoute, digitValue]
  rw [Int.toNat_of_nonneg]
  · omega
  · omega

/-- The familiar tritic word is a later projection of the generated full
nonadic ledger, rather than an input used to select that ledger. -/
theorem tritic_projection_recovers_emission (t : Fin 108) :
    (digitValue (centralDigitalRoute t) % 3).toNat =
      ElectronReturn.emittedAt t.val := by
  rw [central_digit_value]
  rfl

/-- The full generated electronic ledger has the raw Article VI signature
recorded by the corpus.  In particular this is distinct from the later
reader exponent `(80,54,6)` and from the action origin `v_e = 0`. -/
theorem central_signature :
    signature centralDigitalRoute = ![24, 0, 12, 0, -12] := by
  decide

theorem central_action_count : actionCount centralDigitalRoute = 24 := by
  have h := congrFun central_signature (0 : Fin 5)
  simpa [signature] using h

theorem central_event_total : eventTotal centralDigitalRoute = 0 := by
  have h := congrFun central_signature (1 : Fin 5)
  simpa [signature] using h

theorem central_torsion_defect : torsionDefect centralDigitalRoute = 12 := by
  have h := congrFun central_signature (2 : Fin 5)
  simpa [signature] using h

theorem central_tower120 : tower120 centralDigitalRoute = 0 := by
  have h := congrFun central_signature (3 : Fin 5)
  simpa [signature] using h

theorem central_autocorrelation : autocorrelation centralDigitalRoute = -12 := by
  have h := congrFun central_signature (4 : Fin 5)
  simpa [signature] using h

/-- Evaluation of the generated five-integer ledger in the internal Article VI
coordinates.  This is the raw ledger character, not the distinct return-reader
exponent `80 - 54 * alpha + 6 * delta`. -/
theorem central_internal_exponent (x y delta s120 : ℝ) :
    exponent (internalCoordinates x y delta s120)
        (signature centralDigitalRoute) =
      24 * x + 12 * delta - 12 * (135 * delta ^ 2) := by
  rw [internal_exponent, central_signature]
  simp
  ring

/-- The event coordinates read from the generated central ledger remain an
integral, reversible representation of all twelve oriented events. -/
theorem central_events_reconstructed :
    reconstruct (extract (events centralDigitalRoute)) =
      events centralDigitalRoute :=
  ledger_events_reconstruct centralDigitalRoute

theorem central_coordinates_integral :
    IntegralImage (extract (events centralDigitalRoute)) :=
  ledger_coordinates_integral centralDigitalRoute

/-- A one-point typed fibre used only to instantiate the already proved mass
operator on the generated central electronic route. -/
inductive CentralRoute where
  | electron
  deriving DecidableEq, Fintype

def generatedLedger (_ : CentralRoute) : DigitalRoute := centralDigitalRoute

noncomputable section

/-- Posterior evaluation of either already generated electronic reader. -/
def evaluateReturnTriple (triple : Int × Int × Int) (alpha delta : ℝ) : ℝ :=
  (triple.1 : ℝ) - alpha * (triple.2.1 : ℝ) +
    delta * (triple.2.2 : ℝ)

def centralReturnExponentD (alpha delta : ℝ) : ℝ :=
  evaluateReturnTriple
    (ElectronReturn.discrepancyReader ElectronReturn.gamma) alpha delta

def centralReturnExponentOmega (alpha delta : ℝ) : ℝ :=
  evaluateReturnTriple
    (ElectronReturn.windowReader ElectronReturn.tau) alpha delta

theorem central_return_exponents_agree (alpha delta : ℝ) :
    centralReturnExponentD alpha delta =
      centralReturnExponentOmega alpha delta := by
  unfold centralReturnExponentD centralReturnExponentOmega
  rw [ElectronReturn.readers_agree]

theorem central_return_exponent_value (alpha delta : ℝ) :
    centralReturnExponentD alpha delta = 80 - 54 * alpha + 6 * delta := by
  unfold centralReturnExponentD evaluateReturnTriple
  rw [ElectronReturn.discrepancy_reader_central]
  norm_num
  ring

/-- The reader label is retained even though the two readers agree on the
central generated trajectory. -/
def centralReturnExponent (alpha delta : ℝ) :
    Reader → CentralRoute → ℝ
  | .D, _ => centralReturnExponentD alpha delta
  | .Omega, _ => centralReturnExponentOmega alpha delta

theorem central_return_exponent_typed (alpha delta : ℝ)
    (r : Reader) (route : CentralRoute) :
    centralReturnExponent alpha delta r route =
      80 - 54 * alpha + 6 * delta := by
  cases r with
  | D => exact central_return_exponent_value alpha delta
  | Omega =>
      rw [centralReturnExponent]
      rw [← central_return_exponents_agree alpha delta]
      exact central_return_exponent_value alpha delta

/-- Article VI's basal operator, now fed by the generated central ledger
rather than by an arbitrary supplied digital trace. -/
def centralLedgerBasal (mRef x y delta : ℝ)
    (η : Refinement (internalMoments x y)) : End CentralRoute :=
  ledgerBasal mRef x y delta generatedLedger centralDigitalRoute
    (fun _ => η) η

theorem central_ledger_basal_positive {mRef : ℝ} (hmRef : 0 < mRef)
    (x y delta : ℝ) (η : Refinement (internalMoments x y)) :
    (centralLedgerBasal mRef x y delta η).IsPositive :=
  ledgerBasal_positive hmRef x y delta generatedLedger centralDigitalRoute
    (fun _ => η) η

theorem central_ledger_corrected_positive (Ract : ℝ)
    {mRef : ℝ} (hmRef : 0 < mRef)
    (κ : Reader → CentralRoute → ℝ) (r : Reader)
    (x y delta : ℝ) (η : Refinement (internalMoments x y)) :
    (corrected Ract κ r (centralLedgerBasal mRef x y delta η)).IsPositive :=
  ledger_corrected_positive Ract hmRef κ r x y delta generatedLedger
    centralDigitalRoute (fun _ => η) η

theorem central_ledger_corrected_basis {Ract : ℝ} (hRact : 0 < Ract)
    (mRef : ℝ) (κ : Reader → CentralRoute → ℝ) (r : Reader)
    (x y delta : ℝ) (η : Refinement (internalMoments x y)) :
    corrected Ract κ r (centralLedgerBasal mRef x y delta η)
        (routeBasis CentralRoute.electron) =
      (mRef * refinedCharacter
          (internalCoordinates x y delta (internalMoments x y 120))
          (signature centralDigitalRoute - signature centralDigitalRoute)
          (η.sub η) * Ract ^ (κ r CentralRoute.electron) : ℝ) •
        routeBasis CentralRoute.electron := by
  exact ledger_corrected_basis hRact mRef κ r x y delta generatedLedger
    centralDigitalRoute (fun _ => η) η CentralRoute.electron

/-- The corrected operator with the return exponent supplied by the two
generated central readers rather than by an arbitrary scalar function. -/
def centralMassOperator (Ract mRef x y delta alpha : ℝ)
    (r : Reader) (η : Refinement (internalMoments x y)) : End CentralRoute :=
  corrected Ract (centralReturnExponent alpha delta) r
    (centralLedgerBasal mRef x y delta η)

theorem central_mass_operator_positive (Ract : ℝ)
    {mRef : ℝ} (hmRef : 0 < mRef)
    (x y delta alpha : ℝ) (r : Reader)
    (η : Refinement (internalMoments x y)) :
    (centralMassOperator Ract mRef x y delta alpha r η).IsPositive := by
  exact central_ledger_corrected_positive Ract hmRef
    (centralReturnExponent alpha delta) r x y delta η

theorem central_mass_operator_basis {Ract : ℝ} (hRact : 0 < Ract)
    (mRef x y delta alpha : ℝ) (r : Reader)
    (η : Refinement (internalMoments x y)) :
    centralMassOperator Ract mRef x y delta alpha r η
        (routeBasis CentralRoute.electron) =
      (mRef * refinedCharacter
          (internalCoordinates x y delta (internalMoments x y 120))
          (signature centralDigitalRoute - signature centralDigitalRoute)
          (η.sub η) * Ract ^ (80 - 54 * alpha + 6 * delta) : ℝ) •
        routeBasis CentralRoute.electron := by
  unfold centralMassOperator
  rw [central_ledger_corrected_basis hRact]
  rw [central_return_exponent_typed]

end

#print axioms central_digit_value
#print axioms tritic_projection_recovers_emission
#print axioms central_signature
#print axioms central_internal_exponent
#print axioms central_events_reconstructed
#print axioms central_coordinates_integral
#print axioms central_return_exponents_agree
#print axioms central_return_exponent_value
#print axioms central_return_exponent_typed
#print axioms central_ledger_basal_positive
#print axioms central_ledger_corrected_positive
#print axioms central_ledger_corrected_basis
#print axioms central_mass_operator_positive
#print axioms central_mass_operator_basis

end HMT.VI.ElectronGeneratedLedger
