import RefinedMassBridge
import LedgerSignature

/-!
The finite mass operator instantiated with the deterministic five-integer
signature read from supplied digital routes of exactly 108 positions. This
does not assert that every supplied route is generated by TPK, nor that the
signature extractor is additive. Absolute tower data and the fixed reference
are retained separately; their difference is taken exactly once.
-/
namespace HMT.VI.MassOperator.LedgerBridge
noncomputable section

open HMTMassCharacter HMT.VI.LedgerSignature

variable {Route : Type*} [Fintype Route] [DecidableEq Route]

def ledgerBasal (mRef x y delta : ℝ) (d : Route → DigitalRoute) (dRef : DigitalRoute)
    (η : Route → Refinement (internalMoments x y))
    (ηRef : Refinement (internalMoments x y)) : End Route :=
  internalBasal mRef x y delta (fun γ => signature (d γ)) (signature dRef) η ηRef

theorem ledgerBasal_positive {mRef : ℝ} (hm : 0 < mRef)
    (x y delta : ℝ) (d : Route → DigitalRoute) (dRef : DigitalRoute)
    (η : Route → Refinement (internalMoments x y))
    (ηRef : Refinement (internalMoments x y)) :
    (ledgerBasal mRef x y delta d dRef η ηRef).IsPositive :=
  internalBasal_positive hm x y delta _ _ η ηRef

theorem ledger_corrected_positive (Ract : ℝ) {mRef : ℝ} (hm : 0 < mRef)
    (κ : Reader → Route → ℝ) (r : Reader)
    (x y delta : ℝ) (d : Route → DigitalRoute) (dRef : DigitalRoute)
    (η : Route → Refinement (internalMoments x y))
    (ηRef : Refinement (internalMoments x y)) :
    (corrected Ract κ r (ledgerBasal mRef x y delta d dRef η ηRef)).IsPositive :=
  corrected_positive Ract κ r _ (ledgerBasal_positive hm x y delta d dRef η ηRef)

theorem ledger_corrected_basis {Ract : ℝ} (hR : 0 < Ract) (mRef : ℝ)
    (κ : Reader → Route → ℝ) (r : Reader)
    (x y delta : ℝ) (d : Route → DigitalRoute) (dRef : DigitalRoute)
    (η : Route → Refinement (internalMoments x y))
    (ηRef : Refinement (internalMoments x y)) (γ : Route) :
    corrected Ract κ r (ledgerBasal mRef x y delta d dRef η ηRef) (routeBasis γ) =
      (mRef * refinedCharacter (internalCoordinates x y delta (internalMoments x y 120))
        (signature (d γ) - signature dRef) ((η γ).sub ηRef) *
        Ract ^ (κ r γ) : ℝ) • routeBasis γ :=
  internal_corrected_basis hR mRef κ r x y delta _ _ η ηRef γ

omit [Fintype Route] [DecidableEq Route] in
/-- The integral event total enters the signature unchanged; its factor 1/6
belongs to the internal coordinate, not to the digital extractor. -/
theorem ledger_event_coordinate (d : Route → DigitalRoute) (γ : Route) :
    signature (d γ) 1 =
      (HMT.VI.EventReconstruction.extract (events (d γ))).total :=
  signature_total_preserved (d γ)

#print axioms ledgerBasal_positive
#print axioms ledger_corrected_positive
#print axioms ledger_corrected_basis
#print axioms ledger_event_coordinate

end
end HMT.VI.MassOperator.LedgerBridge
