import HexadOctadResidual
import Mathlib.Data.ZMod.Basic
import Mathlib.Data.Finset.Powerset
import Mathlib.Data.Fintype.EquivFin
import Mathlib.Data.Fintype.Sigma

/-!
Concrete classical binary realization for Article I, `exc:residuo-binario`.
This closes the existing `BinaryGolayData` interface. It does not claim that
the cyclic polynomial is generated by HMT or selects any HMT decimal.

The generator is 1+x+x^5+x^6+x^7+x^9+x^11, with twelve shifts in
coordinates 0,...,22 and the even-parity extension in coordinate 23.
Finite native certificates below are explicit and use Lean.ofReduceBool;
no Python result is imported as a proposition.
-/

namespace HMT.I.ConcreteBinaryGolay

open HexadOctadResidual

abbrev Message := Fin 12 → ZMod 2
abbrev Word := Fin 24 → ZMod 2

def generatorExponents : Finset ℕ := {0, 1, 5, 6, 7, 9, 11}

def generator (i : Fin 12) (j : Fin 24) : ZMod 2 :=
  if j.val = 23 then 1
  else if i.val ≤ j.val ∧ j.val - i.val ∈ generatorExponents then 1 else 0

def encode (m : Message) : Word := fun j => ∑ i, m i * generator i j

def wordSupport (w : Word) : Support := Finset.univ.filter fun j => w j ≠ 0

def encodeSupport (m : Message) : Support := wordSupport (encode m)

def codewords : Finset Support := Finset.univ.image encodeSupport

def code : Set Support := ↑codewords

theorem mem_code_iff (s : Support) : s ∈ code ↔ ∃ m, encodeSupport m = s := by
  simp [code, codewords]

/-- Little-endian coefficient chart used by the independent Python check. -/
def messageOfIndex (m : Fin 4096) : Message := fun i =>
  if Nat.testBit m.val i.val then 1 else 0

def encodeIndex (m : Fin 4096) : Support := encodeSupport (messageOfIndex m)

theorem encodeIndex_mem (m : Fin 4096) : encodeIndex m ∈ code :=
  (mem_code_iff _).mpr ⟨messageOfIndex m, rfl⟩

theorem encode_add (m n : Message) : encode (m+n) = encode m + encode n := by
  ext j
  simp [encode, add_mul, Finset.sum_add_distrib]

theorem zmod_two_add_ne_zero (a b : ZMod 2) :
    a+b ≠ 0 ↔ (a ≠ 0 ∧ b = 0) ∨ (b ≠ 0 ∧ a = 0) := by
  revert a b
  decide

theorem support_add (v w : Word) :
    wordSupport (v+w) = binarySum (wordSupport v) (wordSupport w) := by
  ext j
  simp only [wordSupport, binarySum, Finset.mem_filter, Finset.mem_univ, true_and,
    Pi.add_apply, Finset.mem_union, Finset.mem_sdiff, not_not]
  exact zmod_two_add_ne_zero _ _

theorem sum_closed (s : Support) (hs : s ∈ code) (t : Support) (ht : t ∈ code) :
    binarySum s t ∈ code := by
  obtain ⟨m, rfl⟩ := (mem_code_iff s).mp hs
  obtain ⟨n, rfl⟩ := (mem_code_iff t).mp ht
  apply (mem_code_iff _).mpr
  refine ⟨m+n, ?_⟩
  simp only [encodeSupport, encode_add, support_add]

theorem encoded_allowed_weights : ∀ m : Message,
    (encodeSupport m).card = 0 ∨ (encodeSupport m).card = 8 ∨
    (encodeSupport m).card = 12 ∨ (encodeSupport m).card = 16 ∨
    (encodeSupport m).card = 24 := by native_decide

theorem allowed_weights (s : Support) (hs : s ∈ code) :
    s.card = 0 ∨ s.card = 8 ∨ s.card = 12 ∨ s.card = 16 ∨ s.card = 24 := by
  obtain ⟨m, rfl⟩ := (mem_code_iff s).mp hs
  exact encoded_allowed_weights m

def dodecadMessage : Message := fun i => if i.val = 0 ∨ i.val = 3 then 1 else 0

def dodecad : Support := encodeSupport dodecadMessage

theorem dodecad_mem : dodecad ∈ code := (mem_code_iff _).mpr ⟨dodecadMessage, rfl⟩

theorem dodecad_card : dodecad.card = 12 := by native_decide

theorem dodecad_coordinates :
    dodecad = {0, 1, 3, 4, 5, 6, 7, 8, 10, 11, 12, 14} := by native_decide

def octads : Finset Support := codewords.filter fun s => s.card = 8

theorem mem_octads (s : Support) : s ∈ octads ↔ s ∈ code ∧ s.card = 8 := by
  simp [octads, code]

theorem octads_card : octads.card = 759 := by native_decide

theorem codewords_card : codewords.card = 4096 := by native_decide

end HMT.I.ConcreteBinaryGolay

#print axioms HMT.I.ConcreteBinaryGolay.encoded_allowed_weights
#print axioms HMT.I.ConcreteBinaryGolay.sum_closed
#print axioms HMT.I.ConcreteBinaryGolay.octads_card
