import APPFockRigidity
import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Matrix.Mul
import Mathlib.Data.Matrix.Block
import Mathlib.LinearAlgebra.Matrix.Trace

/-!
# The actual finite degree-two APP--Fock index

U030: twelve A₂ factors, six with Coxeter C and six with C⁻¹.
The symmetric-square matrix below is defined by the coefficients of the
induced map on symmetric tensors: eᵢ⊗eᵢ and eᵢ⊗eⱼ+eⱼ⊗eᵢ (i < j),
not by its expected trace.
The APP aggregate is imported from APPFockRigidity and is generated by
the two APP leaves. Only the finite degree-two operator is formalized.
This is not a construction of an infinite Fock space or of a VOA.
-/

namespace HMT.I.APPFockIndex

open Matrix APPFockRigidity

abbrev Coordinate := Fin 24
abbrev QuadraticIndex := {p : Coordinate × Coordinate // p.1 ≤ p.2}

def coxeter : Matrix (Fin 2) (Fin 2) ℚ := !![0, -1; 1, -1]
def coxeterInverse : Matrix (Fin 2) (Fin 2) ℚ := !![-1, 1; -1, 0]

def localCoordinate (i : Coordinate) : Fin 2 :=
  ⟨i.val % 2, Nat.mod_lt _ (by decide)⟩

/-- Direct sum of the twelve oriented A₂ actions. -/
def generator : Matrix Coordinate Coordinate ℚ := fun i j =>
  if i.val / 2 = j.val / 2 then
    if i.val / 2 < 6 then coxeter (localCoordinate i) (localCoordinate j)
    else coxeterInverse (localCoordinate i) (localCoordinate j)
  else 0

def sheetSign (i : Coordinate) : ℚ := if i.val < 12 then 1 else -1

def orientedGenerator : Matrix Coordinate Coordinate ℚ := fun i j =>
  sheetSign i * generator i j

/-- Matrix on the symmetric-tensor basis. Columns are transformed basis
elements; the factor two appears precisely for an off-diagonal input and
diagonal output. This defines the representation, not merely its trace. -/
def symmetricSquare (A : Matrix Coordinate Coordinate ℚ) :
    Matrix QuadraticIndex QuadraticIndex ℚ := fun p q =>
  if q.val.1 = q.val.2 then
    A p.val.1 q.val.1 * A p.val.2 q.val.1
  else if p.val.1 = p.val.2 then
    2 * A p.val.1 q.val.1 * A p.val.1 q.val.2
  else A p.val.1 q.val.1 * A p.val.2 q.val.2 +
    A p.val.1 q.val.2 * A p.val.2 q.val.1

/-- Sheet parity acts on a quadratic monomial by the product of its signs. -/
def quadraticParity : Matrix QuadraticIndex QuadraticIndex ℚ :=
  diagonal (fun p => sheetSign p.val.1 * sheetSign p.val.2)

theorem symmetricSquare_oriented :
    symmetricSquare orientedGenerator = quadraticParity * symmetricSquare generator := by
  ext p q
  simp only [quadraticParity, diagonal_mul, symmetricSquare, orientedGenerator]
  split_ifs with hq hp
  · ring
  · rw [hp]
    ring
  · ring

/-- The positive degree-two Fock piece is V[2] ⊕ Sym²(V[1]). -/
def degreeTwoFockTrace : ℚ := trace generator + trace (symmetricSquare generator)

/-- The zero action on V[2] and 3c(δ) times sheet parity on Sym²(V[1]). -/
def aggregateCoupling : Matrix QuadraticIndex QuadraticIndex ℚ :=
  diagonal (fun p => 3 * (coefficient generatedAggregate : ℚ) *
    (sheetSign p.val.1 * sheetSign p.val.2))

def orientedTrace : ℚ := trace (aggregateCoupling * symmetricSquare generator)

theorem generator_trace : trace generator = -12 := by
  norm_num [trace, diag_apply, Fin.sum_univ_succ, generator,
    localCoordinate, coxeter, coxeterInverse]

theorem oriented_generator_trace : trace orientedGenerator = 0 := by
  norm_num [trace, diag_apply, Fin.sum_univ_succ, orientedGenerator,
    sheetSign, generator, localCoordinate, coxeter, coxeterInverse]

theorem symmetricSquare_trace_sum (A : Matrix Coordinate Coordinate ℚ) :
    trace (symmetricSquare A) =
      ∑ i : Coordinate, ∑ j : Coordinate,
        if i ≤ j then
          if i = j then A i i * A i i else A i i * A j j + A i j * A j i
        else 0 := by
  unfold trace
  simp only [diag_apply, symmetricSquare, ite_self]
  have h := Finset.sum_subtype (F := inferInstanceAs (Fintype QuadraticIndex))
    (Finset.univ.filter (fun p : Coordinate × Coordinate => p.1 ≤ p.2))
    (by simp : ∀ p : Coordinate × Coordinate,
      p ∈ Finset.univ.filter (fun p : Coordinate × Coordinate => p.1 ≤ p.2) ↔
        p.1 ≤ p.2)
    (fun p : Coordinate × Coordinate =>
      if p.1 = p.2 then A p.1 p.1 * A p.1 p.1
      else A p.1 p.1 * A p.2 p.2 + A p.1 p.2 * A p.2 p.1)
  simp only [Finset.sum_filter, Fintype.sum_prod_type] at h
  rw [h]
  apply Finset.sum_congr rfl
  intro p _
  split_ifs with hp
  · rw [hp]
  · rfl

set_option maxRecDepth 20000 in
set_option maxHeartbeats 0 in
theorem symmetric_square_generator_trace : trace (symmetricSquare generator) = 66 := by
  decide +kernel

set_option maxRecDepth 20000 in
set_option maxHeartbeats 0 in
theorem symmetric_square_oriented_trace : trace (symmetricSquare orientedGenerator) = -6 := by
  decide +kernel

theorem degree_two_fock_trace : degreeTwoFockTrace = 54 := by
  rw [degreeTwoFockTrace, generator_trace, symmetric_square_generator_trace]
  norm_num

/-- The actual graded piece: mode two and two copies of mode one. -/
abbrev DegreeTwoIndex := Coordinate ⊕ QuadraticIndex

def degreeTwoOperator : Matrix DegreeTwoIndex DegreeTwoIndex ℚ :=
  fromBlocks generator 0 0 (symmetricSquare generator)

theorem degree_two_operator_trace : trace degreeTwoOperator = 54 := by
  change (∑ i : DegreeTwoIndex, degreeTwoOperator i i) = 54
  rw [Fintype.sum_sum_type]
  change trace generator + trace (symmetricSquare generator) = 54
  exact degree_two_fock_trace

theorem degree_two_trace_radial_norm :
    trace degreeTwoOperator = radialNormPolynomial 12 := by
  rw [degree_two_operator_trace]
  norm_num [radialNormPolynomial]

theorem coupling_trace_eq : orientedTrace =
    3 * (coefficient generatedAggregate : ℚ) * trace (symmetricSquare orientedGenerator) := by
  unfold orientedTrace trace
  simp only [aggregateCoupling, diag_apply, diagonal_mul]
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro p _
  rw [symmetricSquare_oriented]
  simp only [quadraticParity, diagonal_mul]
  ring

theorem generated_app_fock_index : orientedTrace = 54 := by
  rw [coupling_trace_eq, generated_unit_coefficient, symmetric_square_oriented_trace]
  norm_num

theorem operator_index_agrees_with_arithmetic_formula :
    orientedTrace = orientedIndexFormula 12 generatedAggregate :=
  generated_app_fock_index.trans generated_oriented_index.symm

/-- The same source coupling for an arbitrary aggregate, before evaluation. -/
def couplingOf (ν : Aggregate) : Matrix QuadraticIndex QuadraticIndex ℚ :=
  diagonal (fun p => 3 * (coefficient ν : ℚ) *
    (sheetSign p.val.1 * sheetSign p.val.2))

def indexOf (ν : Aggregate) : ℚ := trace (couplingOf ν * symmetricSquare generator)

theorem coupling_zero_perturbation (ν : Aggregate) (k : ℤ) :
    couplingOf (perturbZero ν k) = couplingOf ν := by
  simp only [couplingOf, perturbZero_coefficient]

theorem operator_index_zero_perturbation (ν : Aggregate) (k : ℤ) :
    indexOf (perturbZero ν k) = indexOf ν := by
  simp only [indexOf, coupling_zero_perturbation]

/-- The source falsifier is checked on the full operator, not just its formula. -/
theorem operator_index_not_digital_weight :
    indexOf (perturbZero generatedAggregate 1) = 54 ∧
    digitalWeight (perturbZero generatedAggregate 1) = 63 := by
  constructor
  · rw [operator_index_zero_perturbation]
    exact generated_app_fock_index
  · exact oriented_index_not_digital_weight.2

end HMT.I.APPFockIndex

#print axioms HMT.I.APPFockIndex.symmetricSquare_oriented
#print axioms HMT.I.APPFockIndex.generator_trace
#print axioms HMT.I.APPFockIndex.oriented_generator_trace
#print axioms HMT.I.APPFockIndex.symmetric_square_generator_trace
#print axioms HMT.I.APPFockIndex.symmetric_square_oriented_trace
#print axioms HMT.I.APPFockIndex.degree_two_fock_trace
#print axioms HMT.I.APPFockIndex.symmetricSquare_trace_sum
#print axioms HMT.I.APPFockIndex.degree_two_operator_trace
#print axioms HMT.I.APPFockIndex.degree_two_trace_radial_norm
#print axioms HMT.I.APPFockIndex.coupling_trace_eq
#print axioms HMT.I.APPFockIndex.generated_app_fock_index
#print axioms HMT.I.APPFockIndex.operator_index_agrees_with_arithmetic_formula
#print axioms HMT.I.APPFockIndex.coupling_zero_perturbation
#print axioms HMT.I.APPFockIndex.operator_index_zero_perturbation
#print axioms HMT.I.APPFockIndex.operator_index_not_digital_weight
