import ArticleIIFromSharedBase
import ArticleIIIFromSharedBase
import CKMComplex
import CKMSpectral
import GeneratedAngularData
import QuarterTurn
import SelectedAngularBarbero
import ArticleIIIDimensionalReading
import ArticleIIIIISharedComposition
import CKMMassTransport
import GeneratedCKM
import NormalizedQuarterTurn
import CKMCycle
import OrientedSeries
import GeneratedCKMClosure
import MomentDerivatives
import SelectedCKM
import ArticleIICKMFromSharedBase
import PellSection
import SelectedJointCoupling
import MomentIntegral
import AngularBoundary
import AngularMoment
import PellTangentTripling
import ArticleIIICatalanPellFromSharedBase
#print axioms HMT.CKM.ComplexRealization.CKM
#print axioms HMT.CKM.ComplexRealization.CKM_entries
#print axioms HMT.CKM.ComplexRealization.CKM_jarlskog
#print axioms HMT.CKM.ComplexRealization.CKM_jarlskog_neg_phase
#print axioms HMT.CKM.ComplexRealization.CKM_jarlskog_nonzero
#print axioms HMT.CKM.ComplexRealization.CKM_left_unitary
#print axioms HMT.CKM.ComplexRealization.CKM_mem_unitary
#print axioms HMT.CKM.ComplexRealization.CKM_neg_phase
#print axioms HMT.CKM.ComplexRealization.CKM_right_unitary
#print axioms HMT.CKM.ComplexRealization.M3
#print axioms HMT.CKM.ComplexRealization.R12
#print axioms HMT.CKM.ComplexRealization.R12_left_unitary
#print axioms HMT.CKM.ComplexRealization.R12_right_unitary
#print axioms HMT.CKM.ComplexRealization.R23
#print axioms HMT.CKM.ComplexRealization.R23_left_unitary
#print axioms HMT.CKM.ComplexRealization.R23_right_unitary
#print axioms HMT.CKM.ComplexRealization.U13
#print axioms HMT.CKM.ComplexRealization.U13_left_unitary
#print axioms HMT.CKM.ComplexRealization.U13_right_unitary
#print axioms HMT.CKM.ComplexRealization.conj_mul_phase
#print axioms HMT.CKM.ComplexRealization.conjugate
#print axioms HMT.CKM.ComplexRealization.jarlskog
#print axioms HMT.CKM.ComplexRealization.jarlskog_conjugate
#print axioms HMT.CKM.ComplexRealization.jarlskog_phase_rephase
#print axioms HMT.CKM.ComplexRealization.jarlskog_real
#print axioms HMT.CKM.ComplexRealization.jarlskog_rephase
#print axioms HMT.CKM.ComplexRealization.nonzero_jarlskog_obstructs_real_rephasing
#print axioms HMT.CKM.ComplexRealization.phase
#print axioms HMT.CKM.ComplexRealization.phase_exp
#print axioms HMT.CKM.ComplexRealization.phase_im
#print axioms HMT.CKM.ComplexRealization.phase_mul_conj
#print axioms HMT.CKM.ComplexRealization.phase_neg
#print axioms HMT.CKM.ComplexRealization.phase_re
#print axioms HMT.CKM.ComplexRealization.quartet
#print axioms HMT.CKM.ComplexRealization.quartet_conjugate
#print axioms HMT.CKM.ComplexRealization.quartet_rephase
#print axioms HMT.CKM.ComplexRealization.rephase
#print axioms HMT.CKM.ComplexRealization.rephase_apply
#print axioms HMT.CKM.ComplexRealization.trig_circle
#print axioms HMT.CKM.Spectral.Mat3
#print axioms HMT.CKM.Spectral.commutator
#print axioms HMT.CKM.Spectral.diagonal_commutator_det
#print axioms HMT.CKM.Spectral.diagonal_commutator_entry
#print axioms HMT.CKM.Spectral.hermitian_commutator_det
#print axioms HMT.CKM.Spectral.hermitian_cycle_conjugate
#print axioms HMT.CKM.Spectral.inverse_transport_charpoly
#print axioms HMT.CKM.Spectral.massTransport
#print axioms HMT.CKM.Spectral.massTransport_01
#print axioms HMT.CKM.Spectral.massTransport_12
#print axioms HMT.CKM.Spectral.massTransport_20
#print axioms HMT.CKM.Spectral.massTransport_charpoly
#print axioms HMT.CKM.Spectral.massTransport_commutator
#print axioms HMT.CKM.Spectral.massTransport_cycle_jarlskog
#print axioms HMT.CKM.Spectral.massTransport_hermitian
#print axioms HMT.CKM.Spectral.massTransport_jarlskog_determinant
#print axioms HMT.CKM.Spectral.massTransport_jarlskog_determinant_ne_zero_iff
#print axioms HMT.CKM.Spectral.massTransport_jarlskog_determinant_norm
#print axioms HMT.CKM.Spectral.massTransport_spectrum
#print axioms HMT.CKM.Spectral.rotated_cycle_im
#print axioms HMT.CKM.Spectral.spectralX
#print axioms HMT.CKM.Spectral.spectralXY_determinant
#print axioms HMT.CKM.Spectral.spectralXY_sum
#print axioms HMT.CKM.Spectral.spectralY
#print axioms HMT.CKM.Spectral.spectralZ
#print axioms HMT.CKM.Spectral.spectral_quadratic_factor
#print axioms HMT.CKM.Spectral.unitary_transport_hermitian
#print axioms HMT.CKM.Spectral.unitary_transport_spectrum
#print axioms HMT.II.CKM.Generated.H5_tight
#print axioms HMT.II.CKM.Generated.angular_input_bounds
#print axioms HMT.II.CKM.Generated.conjugate
#print axioms HMT.II.CKM.Generated.coordinates
#print axioms HMT.II.CKM.Generated.direct
#print axioms HMT.II.CKM.Generated.generated_ckm_chain
#print axioms HMT.II.CKM.Generated.generated_ckm_principal_chain
#print axioms HMT.II.CKM.Generated.generated_commutator_determinant
#print axioms HMT.II.CKM.Generated.generated_commutator_nonzero
#print axioms HMT.II.CKM.Generated.generated_jarlskog
#print axioms HMT.II.CKM.Generated.generated_jarlskog_positive
#print axioms HMT.II.CKM.Generated.generated_mass_transport
#print axioms HMT.II.CKM.Generated.generated_mixing_intervals
#print axioms HMT.II.CKM.Generated.generated_no_real_rephasing
#print axioms HMT.II.CKM.Generated.generated_phase_check
#print axioms HMT.II.CKM.Generated.generated_phase_interval
#print axioms HMT.II.CKM.Generated.generated_radian_intervals
#print axioms HMT.II.CKM.Generated.generated_recovery
#print axioms HMT.II.CKM.Generated.generated_sector_evaluation
#print axioms HMT.II.CKM.Generated.generated_sector_incidence
#print axioms HMT.II.CKM.Generated.generated_unitary
#print axioms HMT.II.CKM.Generated.matrix
#print axioms HMT.II.CKM.Generated.mixingDegrees
#print axioms HMT.II.CKM.Generated.mixingRadians
#print axioms HMT.II.CKM.Generated.mixing_degrees_formula
#print axioms HMT.II.CKM.Generated.phaseDegrees
#print axioms HMT.II.CKM.Generated.phaseRadians
#print axioms HMT.II.CKM.Generated.radians
#print axioms HMT.II.CKM.Generated.radians_chamber
#print axioms HMT.II.CKM.Generated.return_tight
#print axioms HMT.II.CKM.Generated.spectralSeparation
#print axioms HMT.II.CKM.Generated.sqrt_character_tight
#print axioms HMT.II.CKM.Generated.torsion
#print axioms HMT.II.CKM.Generated.torsionDegrees
#print axioms HMT.II.CKM.Generated.torsion_positive
#print axioms HMT.II.CKM.Generated.torsion_upper
#print axioms HMT.II.CKM.Generated.transportedMass
#print axioms HMT.II.CKM.Selected.angular_input_bounds
#print axioms HMT.II.CKM.Selected.commutator_determinant
#print axioms HMT.II.CKM.Selected.conjugate
#print axioms HMT.II.CKM.Selected.coordinate_recovery
#print axioms HMT.II.CKM.Selected.coordinates
#print axioms HMT.II.CKM.Selected.direct
#print axioms HMT.II.CKM.Selected.jarlskog_formula
#print axioms HMT.II.CKM.Selected.jarlskog_positive
#print axioms HMT.II.CKM.Selected.mass_spectral_transport
#print axioms HMT.II.CKM.Selected.matrix
#print axioms HMT.II.CKM.Selected.matrix_unitary
#print axioms HMT.II.CKM.Selected.mixingDegrees
#print axioms HMT.II.CKM.Selected.mixingRadians
#print axioms HMT.II.CKM.Selected.mixing_degrees_formula
#print axioms HMT.II.CKM.Selected.mixing_intervals
#print axioms HMT.II.CKM.Selected.no_real_rephasing
#print axioms HMT.II.CKM.Selected.phaseDegrees
#print axioms HMT.II.CKM.Selected.phaseRadians
#print axioms HMT.II.CKM.Selected.phase_check
#print axioms HMT.II.CKM.Selected.phase_interval
#print axioms HMT.II.CKM.Selected.radian_intervals
#print axioms HMT.II.CKM.Selected.radians
#print axioms HMT.II.CKM.Selected.radians_chamber
#print axioms HMT.II.CKM.Selected.same_selected_action_coordinates
#print axioms HMT.II.CKM.Selected.sector_evaluation
#print axioms HMT.II.CKM.Selected.selected_ckm_principal_chain
#print axioms HMT.II.CKM.Selected.spectralSeparation
#print axioms HMT.II.CKM.Selected.torsion
#print axioms HMT.II.CKM.Selected.torsionDegrees
#print axioms HMT.II.CKM.Selected.torsion_positive
#print axioms HMT.II.CKM.Selected.torsion_upper
#print axioms HMT.II.CKM.Selected.transportedMass
#print axioms HMT.II.CKMFromSharedBase.angular_input_bounds
#print axioms HMT.II.CKMFromSharedBase.commutator_determinant
#print axioms HMT.II.CKMFromSharedBase.commutator_nonzero
#print axioms HMT.II.CKMFromSharedBase.coordinate_recovery
#print axioms HMT.II.CKMFromSharedBase.coordinate_sources
#print axioms HMT.II.CKMFromSharedBase.coordinates
#print axioms HMT.II.CKMFromSharedBase.generated_pi_conversion
#print axioms HMT.II.CKMFromSharedBase.incidence_evaluation
#print axioms HMT.II.CKMFromSharedBase.jarlskog_formula
#print axioms HMT.II.CKMFromSharedBase.jarlskog_positive
#print axioms HMT.II.CKMFromSharedBase.mass_transport
#print axioms HMT.II.CKMFromSharedBase.matrix
#print axioms HMT.II.CKMFromSharedBase.mixingDegrees
#print axioms HMT.II.CKMFromSharedBase.mixingRadians
#print axioms HMT.II.CKMFromSharedBase.mixing_degrees_formula
#print axioms HMT.II.CKMFromSharedBase.mixing_intervals
#print axioms HMT.II.CKMFromSharedBase.no_real_rephasing
#print axioms HMT.II.CKMFromSharedBase.phaseDegrees
#print axioms HMT.II.CKMFromSharedBase.phaseRadians
#print axioms HMT.II.CKMFromSharedBase.phase_check
#print axioms HMT.II.CKMFromSharedBase.phase_interval
#print axioms HMT.II.CKMFromSharedBase.principal_ckm_publication
#print axioms HMT.II.CKMFromSharedBase.radian_intervals
#print axioms HMT.II.CKMFromSharedBase.sector_evaluation
#print axioms HMT.II.CKMFromSharedBase.spectralSeparation
#print axioms HMT.II.CKMFromSharedBase.torsionDegrees
#print axioms HMT.II.CKMFromSharedBase.transportedMass
#print axioms HMT.II.CKMFromSharedBase.unitary
#print axioms HMT.II.FromSharedBase.action_angle_covariance
#print axioms HMT.II.FromSharedBase.alpha_uses_shared_register
#print axioms HMT.II.FromSharedBase.angleDegrees
#print axioms HMT.II.FromSharedBase.angleRadians
#print axioms HMT.II.FromSharedBase.angles
#print axioms HMT.II.FromSharedBase.angular_recovery
#print axioms HMT.II.FromSharedBase.barberoValue
#print axioms HMT.II.FromSharedBase.barbero_angular_formula
#print axioms HMT.II.FromSharedBase.barbero_constitutive_factorization
#print axioms HMT.II.FromSharedBase.barbero_degree_formula
#print axioms HMT.II.FromSharedBase.barbero_from_constitutive_response
#print axioms HMT.II.FromSharedBase.barbero_oriented_trace
#print axioms HMT.II.FromSharedBase.barbero_reversed_orientation
#print axioms HMT.II.FromSharedBase.channel_source_formula
#print axioms HMT.II.FromSharedBase.channels
#print axioms HMT.II.FromSharedBase.channels_contractive_ordered
#print axioms HMT.II.FromSharedBase.contraAngleDegrees
#print axioms HMT.II.FromSharedBase.contraAngleRadians
#print axioms HMT.II.FromSharedBase.degree_chamber
#print axioms HMT.II.FromSharedBase.degree_publication
#print axioms HMT.II.FromSharedBase.degree_radian_conversion
#print axioms HMT.II.FromSharedBase.degree_recovery
#print axioms HMT.II.FromSharedBase.pi_is_produced_reader
#print axioms HMT.II.FromSharedBase.principal_angular_barbero_publication
#print axioms HMT.II.FromSharedBase.radian_chamber
#print axioms HMT.III.OrientedMoment.Plane
#print axioms HMT.III.OrientedMoment.angularPrimitive
#print axioms HMT.III.OrientedMoment.angularPrimitive_continuousOn
#print axioms HMT.III.OrientedMoment.angularPrimitive_hasDerivAt
#print axioms HMT.III.OrientedMoment.angular_change_and_parts
#print axioms HMT.III.OrientedMoment.angular_moment
#print axioms HMT.III.OrientedMoment.arctan_pell
#print axioms HMT.III.OrientedMoment.atanKernel_ae
#print axioms HMT.III.OrientedMoment.atanKernel_intervalIntegrable
#print axioms HMT.III.OrientedMoment.catalan
#print axioms HMT.III.OrientedMoment.catalan_integral
#print axioms HMT.III.OrientedMoment.catalan_log_tangent
#print axioms HMT.III.OrientedMoment.catalan_pell_complete
#print axioms HMT.III.OrientedMoment.catalan_pell_value
#print axioms HMT.III.OrientedMoment.catalan_series
#print axioms HMT.III.OrientedMoment.constitutive_relation
#print axioms HMT.III.OrientedMoment.cos_pos_quarter
#print axioms HMT.III.OrientedMoment.cos_shift_product
#print axioms HMT.III.OrientedMoment.cos_triple_product
#print axioms HMT.III.OrientedMoment.cycle12
#print axioms HMT.III.OrientedMoment.cycle_intertwines
#print axioms HMT.III.OrientedMoment.derivativeMajorant_summable
#print axioms HMT.III.OrientedMoment.derivativeSeries_summable
#print axioms HMT.III.OrientedMoment.derivativeSeries_uniform
#print axioms HMT.III.OrientedMoment.derivativeTerm
#print axioms HMT.III.OrientedMoment.derivativeTerm_bound
#print axioms HMT.III.OrientedMoment.derivativeTerm_norm
#print axioms HMT.III.OrientedMoment.euler
#print axioms HMT.III.OrientedMoment.euler_moment
#print axioms HMT.III.OrientedMoment.euler_moment_eventually
#print axioms HMT.III.OrientedMoment.euler_moment_hasDerivAt
#print axioms HMT.III.OrientedMoment.euler_origin_limit
#print axioms HMT.III.OrientedMoment.euler_pell
#print axioms HMT.III.OrientedMoment.euler_right_origin_limit
#print axioms HMT.III.OrientedMoment.existing_response_relation
#print axioms HMT.III.OrientedMoment.kernel
#print axioms HMT.III.OrientedMoment.kernel_pell
#print axioms HMT.III.OrientedMoment.logTan
#print axioms HMT.III.OrientedMoment.logTan_integrable
#print axioms HMT.III.OrientedMoment.logTan_integral_tripling
#print axioms HMT.III.OrientedMoment.logTan_pell_ratio
#print axioms HMT.III.OrientedMoment.logTan_reflection
#print axioms HMT.III.OrientedMoment.logTan_shift_minus_integrable
#print axioms HMT.III.OrientedMoment.logTan_shift_plus_integrable
#print axioms HMT.III.OrientedMoment.logTan_triple
#print axioms HMT.III.OrientedMoment.log_pell_reciprocal
#print axioms HMT.III.OrientedMoment.log_tan_intervalIntegrable
#print axioms HMT.III.OrientedMoment.majorant
#print axioms HMT.III.OrientedMoment.majorant_summable
#print axioms HMT.III.OrientedMoment.moment
#print axioms HMT.III.OrientedMoment.moment_absolute
#print axioms HMT.III.OrientedMoment.moment_continuousOn
#print axioms HMT.III.OrientedMoment.moment_endpoint_limit
#print axioms HMT.III.OrientedMoment.moment_hasDerivAt
#print axioms HMT.III.OrientedMoment.moment_hasDerivAt_quotient
#print axioms HMT.III.OrientedMoment.moment_integral
#print axioms HMT.III.OrientedMoment.moment_regularIntegral
#print axioms HMT.III.OrientedMoment.moment_summable
#print axioms HMT.III.OrientedMoment.moment_tan_continuousOn
#print axioms HMT.III.OrientedMoment.moment_tan_hasDerivAt
#print axioms HMT.III.OrientedMoment.moment_uniform
#print axioms HMT.III.OrientedMoment.moment_zero
#print axioms HMT.III.OrientedMoment.mul_log_tan_continuousAt_zero
#print axioms HMT.III.OrientedMoment.mul_log_tan_factor
#print axioms HMT.III.OrientedMoment.mul_log_tan_origin_limit
#print axioms HMT.III.OrientedMoment.mul_log_tan_quarter_continuous
#print axioms HMT.III.OrientedMoment.normalizedEmbed
#print axioms HMT.III.OrientedMoment.normalizedEmbed_inner
#print axioms HMT.III.OrientedMoment.normalized_cycle_intertwines
#print axioms HMT.III.OrientedMoment.normalized_oriented_coefficient
#print axioms HMT.III.OrientedMoment.normalized_reverse_coefficient
#print axioms HMT.III.OrientedMoment.oriented_coefficient
#print axioms HMT.III.OrientedMoment.pellLambda
#print axioms HMT.III.OrientedMoment.pellLambda_pos
#print axioms HMT.III.OrientedMoment.pellRho
#print axioms HMT.III.OrientedMoment.pellRho_lt_one
#print axioms HMT.III.OrientedMoment.pellRho_pos
#print axioms HMT.III.OrientedMoment.pell_log_tangent
#print axioms HMT.III.OrientedMoment.pell_moment_integral
#print axioms HMT.III.OrientedMoment.pell_norm
#print axioms HMT.III.OrientedMoment.pell_reciprocal
#print axioms HMT.III.OrientedMoment.pell_sum_reciprocal
#print axioms HMT.III.OrientedMoment.pencilMatrix
#print axioms HMT.III.OrientedMoment.pencil_determinant
#print axioms HMT.III.OrientedMoment.quarter
#print axioms HMT.III.OrientedMoment.quarter_apply
#print axioms HMT.III.OrientedMoment.quarter_even_iterate
#print axioms HMT.III.OrientedMoment.quarter_four
#print axioms HMT.III.OrientedMoment.quarter_odd_character
#print axioms HMT.III.OrientedMoment.quarter_odd_iterate
#print axioms HMT.III.OrientedMoment.quarter_sq
#print axioms HMT.III.OrientedMoment.regularAtanKernel
#print axioms HMT.III.OrientedMoment.regularAtanKernel_continuous
#print axioms HMT.III.OrientedMoment.regularAtanKernel_eq
#print axioms HMT.III.OrientedMoment.regularAtanKernel_zero
#print axioms HMT.III.OrientedMoment.resolvent
#print axioms HMT.III.OrientedMoment.resolvent_formula
#print axioms HMT.III.OrientedMoment.resolvent_left
#print axioms HMT.III.OrientedMoment.resolvent_right
#print axioms HMT.III.OrientedMoment.reversed_coefficient
#print axioms HMT.III.OrientedMoment.reversed_determinant
#print axioms HMT.III.OrientedMoment.second_euler_moment
#print axioms HMT.III.OrientedMoment.second_euler_pell
#print axioms HMT.III.OrientedMoment.sin_shift_product
#print axioms HMT.III.OrientedMoment.sin_triple_product
#print axioms HMT.III.OrientedMoment.sqrt_three_sq
#print axioms HMT.III.OrientedMoment.tan_dslope_zero
#print axioms HMT.III.OrientedMoment.tan_pi_twelfth
#print axioms HMT.III.OrientedMoment.tan_quarter_bounds
#print axioms HMT.III.OrientedMoment.tan_quarter_continuous
#print axioms HMT.III.OrientedMoment.tan_quarter_interior
#print axioms HMT.III.OrientedMoment.tangent_triple_product
#print axioms HMT.III.OrientedMoment.term
#print axioms HMT.III.OrientedMoment.term_bound
#print axioms HMT.III.OrientedMoment.term_from_character
#print axioms HMT.III.OrientedMoment.term_hasDerivAt
#print axioms HMT.III.OrientedMoment.term_norm
#print axioms HMT.III.OrientedMoment.twelveEmbed
#print axioms HMT.III.OrientedMoment.twelveEmbed_injective
#print axioms HMT.III.OrientedMoment.twelveEmbed_inner
#print axioms HMT.III.OrientedMoment.weighted_derivativeSeries
#print axioms HMT.SelectedAngularBarbero.selected_action_incidence_functional
#print axioms HMT.SelectedAngularBarbero.selected_angular_coordinates
#print axioms HMT.SelectedAngularBarbero.selected_angular_functional
#print axioms HMT.SelectedAngularBarbero.selected_arithmetic_formula
#print axioms HMT.SelectedAngularBarbero.selected_channels_formula
#print axioms HMT.SelectedAngularBarbero.selected_constitutive_recovery
#print axioms HMT.SelectedAngularBarbero.selected_nonadic_recovery
#print axioms HMT.SelectedAngularBarbero.value
#print axioms HMT.SelectedJointCoupling.selected_angular_coordinate_identity
#print axioms HMT.SelectedJointCoupling.selected_barbero_ckm_functional
#print axioms HMT.SelectedJointCoupling.selected_joint_coupling
#print axioms HMT.Shared.ArticleIII.CatalanPell.orientedCoefficient
#print axioms HMT.Shared.ArticleIII.CatalanPell.pell_complete_in_constructed_pi
#print axioms HMT.Shared.ArticleIII.CatalanPell.pell_integral_evaluation
#print axioms HMT.Shared.ArticleIII.CatalanPell.responseWeight
#print axioms HMT.Shared.ArticleIII.CatalanPell.sMinus
#print axioms HMT.Shared.ArticleIII.CatalanPell.sPlus
#print axioms HMT.Shared.ArticleIII.CatalanPell.selected_arguments_mem
#print axioms HMT.Shared.ArticleIII.CatalanPell.selected_moment_integrals
#print axioms HMT.Shared.ArticleIII.CatalanPell.selected_response_arguments
#print axioms HMT.Shared.ArticleIII.CatalanPell.selected_response_from_moment
#print axioms HMT.Shared.ArticleIII.CatalanPell.selected_response_from_resolvent
#print axioms HMT.Shared.ArticleIII.CatalanPell.selected_second_euler_coefficients
#print axioms HMT.Shared.ArticleIII.CatalanPell.selected_series_from_character
#print axioms HMT.Shared.ArticleIII.CatalanPell.shared_catalan_pell_publication
#print axioms HMT.Shared.ArticleIII.Dimensional.PosUnitSections
#print axioms HMT.Shared.ArticleIII.Dimensional.PosUnitSections.action_ne_zero
#print axioms HMT.Shared.ArticleIII.Dimensional.PosUnitSections.charge_ne_zero
#print axioms HMT.Shared.ArticleIII.Dimensional.PosUnitSections.rescale
#print axioms HMT.Shared.ArticleIII.Dimensional.PosUnitSections.velocity_ne_zero
#print axioms HMT.Shared.ArticleIII.Dimensional.Reading
#print axioms HMT.Shared.ArticleIII.Dimensional.Reading.Constitutive
#print axioms HMT.Shared.ArticleIII.Dimensional.Reading.Positive
#print axioms HMT.Shared.ArticleIII.Dimensional.dimensional_after_normalized
#print axioms HMT.Shared.ArticleIII.Dimensional.dimensional_covariance
#print axioms HMT.Shared.ArticleIII.Dimensional.normalized
#print axioms HMT.Shared.ArticleIII.Dimensional.normalized_after_dimensional
#print axioms HMT.Shared.ArticleIII.Dimensional.normalized_constitutive
#print axioms HMT.Shared.ArticleIII.Dimensional.normalized_positive
#print axioms HMT.Shared.ArticleIII.Dimensional.rechart
#print axioms HMT.Shared.ArticleIII.Dimensional.rechart_reversible
#print axioms HMT.Shared.ArticleIII.Dimensional.rechart_selected
#print axioms HMT.Shared.ArticleIII.Dimensional.selected
#print axioms HMT.Shared.ArticleIII.Dimensional.selected_chart_recovery
#print axioms HMT.Shared.ArticleIII.Dimensional.selected_constitutive
#print axioms HMT.Shared.ArticleIII.Dimensional.selected_dimensional_publication
#print axioms HMT.Shared.ArticleIII.Dimensional.selected_positive
#print axioms HMT.Shared.ArticleIII.Dimensional.toDimensional
#print axioms HMT.Shared.ArticleIII.Dimensional.toDimensional_constitutive
#print axioms HMT.Shared.ArticleIII.Dimensional.toDimensional_positive
#print axioms HMT.Shared.ArticleIII.Dimensional.toNormalized
#print axioms HMT.Shared.ArticleIII.Dimensional.toNormalized_positive
#print axioms HMT.Shared.ArticleIII.alpha_uses_shared_register
#print axioms HMT.Shared.ArticleIII.angle_order
#print axioms HMT.Shared.ArticleIII.angles
#print axioms HMT.Shared.ArticleIII.angles_from_selected_constants
#print axioms HMT.Shared.ArticleIII.channels
#print axioms HMT.Shared.ArticleIII.channels_from_selected_constants
#print axioms HMT.Shared.ArticleIII.constitutiveOperator
#print axioms HMT.Shared.ArticleIII.constitutive_identities
#print axioms HMT.Shared.ArticleIII.constitutive_recovers_action_shape
#print axioms HMT.Shared.ArticleIII.constructed_pi_recognition
#print axioms HMT.Shared.ArticleIII.coordinates_from_response
#print axioms HMT.Shared.ArticleIII.coordinates_positive
#print axioms HMT.Shared.ArticleIII.cubic_roots_exist_unique
#print axioms HMT.Shared.ArticleIII.epsilon
#print axioms HMT.Shared.ArticleIII.gamma
#print axioms HMT.Shared.ArticleIII.gamma_at_every_refinement
#print axioms HMT.Shared.ArticleIII.gamma_from_constitutive_readings
#print axioms HMT.Shared.ArticleIII.gamma_from_selected_angles
#print axioms HMT.Shared.ArticleIII.impedance
#print axioms HMT.Shared.ArticleIII.inverse_readings
#print axioms HMT.Shared.ArticleIII.inverse_recovers_channels
#print axioms HMT.Shared.ArticleIII.inverse_recovers_selected_degrees
#print axioms HMT.Shared.ArticleIII.kinetic_speed_is_constitutive
#print axioms HMT.Shared.ArticleIII.mu
#print axioms HMT.Shared.ArticleIII.operator_completion_unique
#print axioms HMT.Shared.ArticleIII.operator_positive
#print axioms HMT.Shared.ArticleIII.oriented_exchange
#print axioms HMT.Shared.ArticleIII.positive_coordinates_exist_unique
#print axioms HMT.Shared.ArticleIII.response_from_channels
#print axioms HMT.Shared.ArticleIII.response_order
#print axioms HMT.Shared.ArticleIII.shared_constitutive_publication
#print axioms HMT.Shared.ArticleIII.speed
#print axioms HMT.Shared.ArticleIII.speed_at_every_refinement
#print axioms HMT.Shared.ArticleIII.vacuum
#print axioms HMT.Shared.ArticleIIIII.barbero_recovered_from_shared_vacuum
#print axioms HMT.Shared.ArticleIIIII.same_angular_chamber
#print axioms HMT.Shared.ArticleIIIII.same_barbero_functional
#print axioms HMT.Shared.ArticleIIIII.same_oriented_channels
